import type { PyqSeedItem } from "./types";

// JNVST Class 6 practice question set — 2023 cohort.
//
// These are ORIGINAL practice questions written in the style/difficulty
// pattern commonly associated with JNVST Class 6, NOT verbatim reproductions
// of any real official NVS past paper. "2023" is only this practice-set's
// cohort label within the parallel 2021-2025 year-batches feeding the shared
// question bank — there is no verified, licensed source for actual leaked or
// official JNVST papers behind this content.
export const posts: PyqSeedItem[] = [
  // ── Mental Ability (8) ──────────────────────────────────────────────
  {
    key: "jnvst-2023-ma-01",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Find the missing number in the series: 3, 6, 9, 12, ?, 18",
      hi: "श्रृंखला में लुप्त संख्या ज्ञात करें: 3, 6, 9, 12, ?, 18",
      mr: "मालिकेतील लुप्त संख्या शोधा: 3, 6, 9, 12, ?, 18",
      bn: "ধারায় অনুপস্থিত সংখ্যাটি খুঁজুন: 3, 6, 9, 12, ?, 18",
      ta: "தொடரில் விடுபட்ட எண்ணைக் கண்டறியவும்: 3, 6, 9, 12, ?, 18",
    },
    optionsJson: [
      { en: "14", hi: "14", mr: "14", bn: "14", ta: "14" },
      { en: "15", hi: "15", mr: "15", bn: "15", ta: "15" },
      { en: "16", hi: "16", mr: "16", bn: "16", ta: "16" },
      { en: "21", hi: "21", mr: "21", bn: "21", ta: "21" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The series increases by 3 each time: 3+3=6, 6+3=9, 9+3=12, 12+3=15. So 21 would be too large and 14 or 16 break the +3 pattern.",
      hi: "श्रृंखला में हर बार 3 जोड़ा जाता है: 3+3=6, 6+3=9, 9+3=12, 12+3=15। इसलिए 21 बहुत बड़ी है और 14 या 16 +3 के पैटर्न को तोड़ते हैं।",
      mr: "मालिकेत दर वेळी 3 मिळवले जातात: 3+3=6, 6+3=9, 9+3=12, 12+3=15. त्यामुळे 21 खूप मोठी आहे आणि 14 किंवा 16 +3 च्या पॅटर्नला मोडतात.",
      bn: "ধারাটিতে প্রতিবার 3 যোগ করা হয়: 3+3=6, 6+3=9, 9+3=12, 12+3=15। তাই 21 অনেক বড় এবং 14 বা 16 +3 প্যাটার্ন ভাঙে।",
      ta: "தொடரில் ஒவ்வொரு முறையும் 3 கூட்டப்படுகிறது: 3+3=6, 6+3=9, 9+3=12, 12+3=15. எனவே 21 மிக அதிகமாகும், 14 அல்லது 16 +3 வடிவத்தை மீறுகின்றன.",
    },
  },
  {
    key: "jnvst-2023-ma-02",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Find the missing letter in the series: B, D, F, H, ?",
      hi: "श्रृंखला में लुप्त अक्षर ज्ञात करें: B, D, F, H, ?",
      mr: "मालिकेतील लुप्त अक्षर शोधा: B, D, F, H, ?",
      bn: "ধারায় অনুপস্থিত অক্ষরটি খুঁজুন: B, D, F, H, ?",
      ta: "தொடரில் விடுபட்ட எழுத்தைக் கண்டறியவும்: B, D, F, H, ?",
    },
    optionsJson: [
      { en: "I", hi: "I", mr: "I", bn: "I", ta: "I" },
      { en: "J", hi: "J", mr: "J", bn: "J", ta: "J" },
      { en: "K", hi: "K", mr: "K", bn: "K", ta: "K" },
      { en: "G", hi: "G", mr: "G", bn: "G", ta: "G" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "Each letter skips one letter of the alphabet (a jump of +2 positions): B→D→F→H→J. Option I is only +1 from H (breaks the skip-one pattern), K is +3 from H (skips two), and G would mean going backward.",
      hi: "प्रत्येक अक्षर वर्णमाला का एक अक्षर छोड़ता है (+2 स्थान की छलांग): B→D→F→H→J। विकल्प I, H से केवल +1 है (एक-छोड़ने के पैटर्न को तोड़ता है), K, H से +3 है (दो अक्षर छोड़ता है), और G का अर्थ पीछे जाना होगा।",
      mr: "प्रत्येक अक्षर वर्णमालेतील एक अक्षर वगळते (+2 स्थानांची उडी): B→D→F→H→J. पर्याय I हा H पासून फक्त +1 आहे (एक-वगळण्याचा पॅटर्न मोडतो), K हा H पासून +3 आहे (दोन अक्षरे वगळतो), आणि G म्हणजे मागे जाणे होईल.",
      bn: "প্রতিটি অক্ষর বর্ণমালার একটি অক্ষর বাদ দেয় (+2 অবস্থানের লাফ): B→D→F→H→J। বিকল্প I, H থেকে মাত্র +1 (একটি-বাদ-দেওয়ার প্যাটার্ন ভাঙে), K, H থেকে +3 (দুটি অক্ষর বাদ দেয়), এবং G মানে পিছনে যাওয়া।",
      ta: "ஒவ்வொரு எழுத்தும் அகரவரிசையில் ஒரு எழுத்தைத் தவிர்க்கிறது (+2 இட தாவல்): B→D→F→H→J. விருப்பம் I என்பது H இலிருந்து +1 மட்டுமே (ஒன்று-தவிர்க்கும் முறையை மீறுகிறது), K என்பது H இலிருந்து +3 (இரண்டு எழுத்துகளைத் தவிர்க்கிறது), G எனில் பின்னோக்கிச் செல்வதாகும்.",
    },
  },
  {
    key: "jnvst-2023-ma-03",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Which one does not belong with the others: Rose, Lotus, Jasmine, Mango?",
      hi: "इनमें से कौन-सा अन्य से मेल नहीं खाता: गुलाब, कमल, चमेली, आम?",
      mr: "यापैकी कोणता इतरांशी जुळत नाही: गुलाब, कमळ, चमेली, आंबा?",
      bn: "এর মধ্যে কোনটি অন্যদের সাথে মেলে না: গোলাপ, পদ্ম, চামেলি, আম?",
      ta: "இவற்றில் எது மற்றவற்றுடன் பொருந்தவில்லை: ரோஜா, தாமரை, மல்லிகை, மாம்பழம்?",
    },
    optionsJson: [
      { en: "Rose", hi: "गुलाब", mr: "गुलाब", bn: "গোলাপ", ta: "ரோஜா" },
      { en: "Lotus", hi: "कमल", mr: "कमळ", bn: "পদ্ম", ta: "தாமரை" },
      { en: "Jasmine", hi: "चमेली", mr: "चमेली", bn: "চামেলি", ta: "மல்லிகை" },
      { en: "Mango", hi: "आम", mr: "आंबा", bn: "আম", ta: "மாம்பழம்" },
    ],
    correctAnswer: 3,
    explanation: {
      en: "Rose, Lotus, and Jasmine are all flowers; Mango is a fruit, so it does not belong with the group.",
      hi: "गुलाब, कमल और चमेली सभी फूल हैं; आम एक फल है, इसलिए यह समूह से मेल नहीं खाता।",
      mr: "गुलाब, कमळ आणि चमेली ही सर्व फुले आहेत; आंबा हे फळ आहे, त्यामुळे ते या गटाशी जुळत नाही.",
      bn: "গোলাপ, পদ্ম এবং চামেলি সবই ফুল; আম একটি ফল, তাই এটি এই দলের সাথে মেলে না।",
      ta: "ரோஜா, தாமரை, மல்லிகை ஆகியவை மலர்கள்; மாம்பழம் ஒரு பழம், எனவே இது இந்தக் குழுவுடன் பொருந்தவில்லை.",
    },
  },
  {
    key: "jnvst-2023-ma-04",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Doctor is to Hospital as Teacher is to ?",
      hi: "डॉक्टर का अस्पताल से वही संबंध है जो शिक्षक का किससे है?",
      mr: "डॉक्टरचा रुग्णालयाशी जसा संबंध आहे, तसा शिक्षकाचा कशाशी आहे?",
      bn: "ডাক্তারের সাথে হাসপাতালের যে সম্পর্ক, শিক্ষকের সাথে তার সম্পর্ক কীসের সাথে?",
      ta: "மருத்துவருக்கும் மருத்துவமனைக்கும் உள்ள தொடர்பு போல, ஆசிரியருக்கும் எதற்கும் தொடர்பு உள்ளது?",
    },
    optionsJson: [
      { en: "School", hi: "स्कूल", mr: "शाळा", bn: "স্কুল", ta: "பள்ளி" },
      { en: "Hospital", hi: "अस्पताल", mr: "रुग्णालय", bn: "হাসপাতাল", ta: "மருத்துவமனை" },
      { en: "Office", hi: "कार्यालय", mr: "कार्यालय", bn: "অফিস", ta: "அலுவலகம்" },
      { en: "Clinic", hi: "क्लीनिक", mr: "दवाखाना", bn: "ক্লিনিক", ta: "கிளினிக்" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "A doctor's workplace is a Hospital; similarly, a teacher's workplace is a School. Hospital and Clinic are both healthcare workplaces (the wrong category, reused from the first pair), and Office is too generic — it is not specific to teaching.",
      hi: "डॉक्टर का कार्यस्थल अस्पताल है; उसी प्रकार, शिक्षक का कार्यस्थल स्कूल है। अस्पताल और क्लीनिक दोनों स्वास्थ्य-सेवा से जुड़े कार्यस्थल हैं (गलत श्रेणी, पहली जोड़ी से दोहराई गई), और कार्यालय बहुत सामान्य है — यह शिक्षण के लिए विशिष्ट नहीं है।",
      mr: "डॉक्टरचे कार्यस्थळ रुग्णालय आहे; त्याचप्रमाणे, शिक्षकाचे कार्यस्थळ शाळा आहे. रुग्णालय आणि दवाखाना दोन्ही आरोग्यसेवेशी संबंधित कार्यस्थळे आहेत (चुकीची श्रेणी, पहिल्या जोडीतून पुनरावृत्ती), आणि कार्यालय खूप सर्वसाधारण आहे — ते शिकवण्यासाठी विशिष्ट नाही.",
      bn: "একজন ডাক্তারের কর্মস্থল হাসপাতাল; একইভাবে, একজন শিক্ষকের কর্মস্থল স্কুল। হাসপাতাল এবং ক্লিনিক উভয়ই স্বাস্থ্যসেবা সংক্রান্ত কর্মস্থল (ভুল বিভাগ, প্রথম জোড়া থেকে পুনরাবৃত্তি), এবং অফিস অত্যন্ত সাধারণ — এটি শিক্ষকতার জন্য নির্দিষ্ট নয়।",
      ta: "மருத்துவரின் பணியிடம் மருத்துவமனை; அதேபோல, ஆசிரியரின் பணியிடம் பள்ளி. மருத்துவமனை மற்றும் கிளினிக் இரண்டும் சுகாதாரப் பணியிடங்கள் (தவறான வகை, முதல் ஜோடியிலிருந்து மீண்டும்), அலுவலகம் மிகவும் பொதுவானது — இது கற்பித்தலுக்கு குறிப்பிட்டதல்ல.",
    },
  },
  {
    key: "jnvst-2023-ma-05",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "If CAT is coded as DBU, how is DOG coded in the same language?",
      hi: "यदि CAT को DBU के रूप में कोडित किया जाता है, तो उसी भाषा में DOG को कैसे कोडित किया जाएगा?",
      mr: "जर CAT ला DBU असे कोडित केले असेल, तर त्याच भाषेत DOG कसे कोडित केले जाईल?",
      bn: "যদি CAT-কে DBU হিসেবে কোড করা হয়, তাহলে একই ভাষায় DOG-কে কীভাবে কোড করা হবে?",
      ta: "CAT என்பது DBU என்று குறியீடு செய்யப்பட்டால், அதே மொழியில் DOG எவ்வாறு குறியீடு செய்யப்படும்?",
    },
    optionsJson: [
      { en: "EPH", hi: "EPH", mr: "EPH", bn: "EPH", ta: "EPH" },
      { en: "EPG", hi: "EPG", mr: "EPG", bn: "EPG", ta: "EPG" },
      { en: "DPH", hi: "DPH", mr: "DPH", bn: "DPH", ta: "DPH" },
      { en: "EQH", hi: "EQH", mr: "EQH", bn: "EQH", ta: "EQH" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Each letter is shifted forward by one place in the alphabet: C→D, A→B, T→U. Applying the same rule to DOG: D→E, O→P, G→H, giving EPH. EPG wrongly leaves the last letter unshifted, DPH wrongly leaves the first letter unshifted, and EQH wrongly shifts O by two places instead of one.",
      hi: "प्रत्येक अक्षर को वर्णमाला में एक स्थान आगे खिसकाया जाता है: C→D, A→B, T→U। DOG पर वही नियम लगाने पर: D→E, O→P, G→H, जिससे EPH प्राप्त होता है। EPG गलती से अंतिम अक्षर को नहीं खिसकाता, DPH गलती से पहले अक्षर को नहीं खिसकाता, और EQH गलती से O को एक की बजाय दो स्थान खिसकाता है।",
      mr: "प्रत्येक अक्षर वर्णमालेत एक स्थान पुढे सरकवले जाते: C→D, A→B, T→U. DOG वर तोच नियम लावल्यास: D→E, O→P, G→H, ज्यामुळे EPH मिळते. EPG चुकून शेवटचे अक्षर न सरकवता ठेवते, DPH चुकून पहिले अक्षर न सरकवता ठेवते, आणि EQH चुकून O ला एकाऐवजी दोन स्थान सरकवते.",
      bn: "প্রতিটি অক্ষরকে বর্ণমালায় একটি স্থান এগিয়ে সরানো হয়: C→D, A→B, T→U। DOG-এ একই নিয়ম প্রয়োগ করলে: D→E, O→P, G→H, যা থেকে EPH পাওয়া যায়। EPG ভুলভাবে শেষ অক্ষরটি না সরিয়ে রাখে, DPH ভুলভাবে প্রথম অক্ষরটি না সরিয়ে রাখে, এবং EQH ভুলভাবে O-কে একের বদলে দুই স্থান সরায়।",
      ta: "ஒவ்வொரு எழுத்தும் அகரவரிசையில் ஒரு இடம் முன்னோக்கி நகர்த்தப்படுகிறது: C→D, A→B, T→U. அதே விதியை DOG-க்குப் பயன்படுத்த: D→E, O→P, G→H, இதனால் EPH கிடைக்கிறது. EPG தவறாக கடைசி எழுத்தை நகர்த்தாமல் விடுகிறது, DPH தவறாக முதல் எழுத்தை நகர்த்தாமல் விடுகிறது, EQH தவறாக O-வை ஒன்றுக்கு பதிலாக இரண்டு இடங்கள் நகர்த்துகிறது.",
    },
  },
  {
    key: "jnvst-2023-ma-06",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Find the missing number in the pattern: 2, 5, 10, 17, 26, ?",
      hi: "पैटर्न में लुप्त संख्या ज्ञात करें: 2, 5, 10, 17, 26, ?",
      mr: "पॅटर्नमधील लुप्त संख्या शोधा: 2, 5, 10, 17, 26, ?",
      bn: "প্যাটার্নে অনুপস্থিত সংখ্যাটি খুঁজুন: 2, 5, 10, 17, 26, ?",
      ta: "வடிவத்தில் விடுபட்ட எண்ணைக் கண்டறியவும்: 2, 5, 10, 17, 26, ?",
    },
    optionsJson: [
      { en: "35", hi: "35", mr: "35", bn: "35", ta: "35" },
      { en: "36", hi: "36", mr: "36", bn: "36", ta: "36" },
      { en: "37", hi: "37", mr: "37", bn: "37", ta: "37" },
      { en: "39", hi: "39", mr: "39", bn: "39", ta: "39" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "The differences between consecutive terms increase by 2 each time: 5−2=3, 10−5=5, 17−10=7, 26−17=9, so the next difference is 11, giving 26+11=37. (Each term is also one more than a perfect square: 1²+1, 2²+1, 3²+1... so the 6th term is 6²+1=37.) 36 is a trap for students who forget the '+1' and just take 6², while 35 and 39 come from miscounting the difference pattern.",
      hi: "क्रमागत पदों के बीच का अंतर हर बार 2 से बढ़ता है: 5−2=3, 10−5=5, 17−10=7, 26−17=9, इसलिए अगला अंतर 11 है, जिससे 26+11=37 प्राप्त होता है। (प्रत्येक पद एक पूर्ण वर्ग से एक अधिक भी है: 1²+1, 2²+1, 3²+1... इसलिए छठा पद 6²+1=37 है।) 36 उन छात्रों के लिए जाल है जो '+1' भूल जाते हैं और केवल 6² लेते हैं, जबकि 35 और 39 अंतर के पैटर्न को गलत गिनने से आते हैं।",
      mr: "सलग पदांमधील फरक दर वेळी 2 ने वाढतो: 5−2=3, 10−5=5, 17−10=7, 26−17=9, त्यामुळे पुढील फरक 11 आहे, ज्यामुळे 26+11=37 मिळते. (प्रत्येक पद एका पूर्ण वर्गापेक्षा एकाने जास्त आहे: 1²+1, 2²+1, 3²+1... त्यामुळे सहावे पद 6²+1=37 आहे.) 36 हा त्या विद्यार्थ्यांसाठी सापळा आहे जे '+1' विसरतात आणि फक्त 6² घेतात, तर 35 आणि 39 फरकाचा पॅटर्न चुकीचा मोजल्याने येतात.",
      bn: "পরপর পদগুলির মধ্যে পার্থক্য প্রতিবার 2 করে বাড়ে: 5−2=3, 10−5=5, 17−10=7, 26−17=9, তাই পরবর্তী পার্থক্য 11, যা থেকে 26+11=37 পাওয়া যায়। (প্রতিটি পদ একটি পূর্ণ বর্গের চেয়ে একটি বেশিও: 1²+1, 2²+1, 3²+1... তাই ষষ্ঠ পদটি 6²+1=37।) 36 তাদের জন্য একটি ফাঁদ যারা '+1' ভুলে যায় এবং শুধু 6² নেয়, আর 35 এবং 39 পার্থক্যের প্যাটার্ন ভুল গণনা থেকে আসে।",
      ta: "தொடர்ச்சியான உறுப்புகளுக்கு இடையேயான வேறுபாடு ஒவ்வொரு முறையும் 2ஆல் அதிகரிக்கிறது: 5−2=3, 10−5=5, 17−10=7, 26−17=9, எனவே அடுத்த வேறுபாடு 11, இதனால் 26+11=37 கிடைக்கிறது. (ஒவ்வொரு உறுப்பும் ஒரு முழு வர்க்கத்தை விட ஒன்று அதிகம்: 1²+1, 2²+1, 3²+1... எனவே ஆறாவது உறுப்பு 6²+1=37.) 36 என்பது '+1'ஐ மறந்து 6² மட்டும் எடுக்கும் மாணவர்களுக்கான பொறியாகும், 35 மற்றும் 39 வேறுபாட்டு முறையை தவறாக எண்ணுவதால் வருகின்றன.",
    },
  },
  {
    key: "jnvst-2023-ma-07",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "HARD",
    questionJson: {
      en: "Find the missing number in the series: 1, 2, 6, 24, 120, ?",
      hi: "श्रृंखला में लुप्त संख्या ज्ञात करें: 1, 2, 6, 24, 120, ?",
      mr: "मालिकेतील लुप्त संख्या शोधा: 1, 2, 6, 24, 120, ?",
      bn: "ধারায় অনুপস্থিত সংখ্যাটি খুঁজুন: 1, 2, 6, 24, 120, ?",
      ta: "தொடரில் விடுபட்ட எண்ணைக் கண்டறியவும்: 1, 2, 6, 24, 120, ?",
    },
    optionsJson: [
      { en: "620", hi: "620", mr: "620", bn: "620", ta: "620" },
      { en: "700", hi: "700", mr: "700", bn: "700", ta: "700" },
      { en: "720", hi: "720", mr: "720", bn: "720", ta: "720" },
      { en: "840", hi: "840", mr: "840", bn: "840", ta: "840" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "Each term is multiplied by the next counting number to get the following term: 1×2=2, 2×3=6, 6×4=24, 24×5=120, so 120×6=720. (This is the factorial sequence: 1!, 2!, 3!, 4!, 5!, 6!.) 840 comes from multiplying by 7 instead of 6, and 620/700 are close but do not follow the multiplication rule at all.",
      hi: "अगला पद पाने के लिए प्रत्येक पद को अगली गिनती संख्या से गुणा किया जाता है: 1×2=2, 2×3=6, 6×4=24, 24×5=120, इसलिए 120×6=720। (यह एक भाज्य (factorial) श्रृंखला है: 1!, 2!, 3!, 4!, 5!, 6!।) 840, 6 की जगह 7 से गुणा करने से आता है, जबकि 620/700 करीब तो हैं पर गुणा के नियम का बिल्कुल पालन नहीं करते।",
      mr: "पुढील पद मिळवण्यासाठी प्रत्येक पदाला पुढील मोजणी संख्येने गुणले जाते: 1×2=2, 2×3=6, 6×4=24, 24×5=120, त्यामुळे 120×6=720. (ही भाज्य (factorial) मालिका आहे: 1!, 2!, 3!, 4!, 5!, 6!.) 840 हे 6 ऐवजी 7 ने गुणल्याने येते, तर 620/700 जवळ असले तरी गुणाकाराच्या नियमाचे अजिबात पालन करत नाहीत.",
      bn: "পরবর্তী পদ পেতে প্রতিটি পদকে পরবর্তী গণনা সংখ্যা দিয়ে গুণ করা হয়: 1×2=2, 2×3=6, 6×4=24, 24×5=120, তাই 120×6=720। (এটি একটি ফ্যাক্টোরিয়াল ধারা: 1!, 2!, 3!, 4!, 5!, 6!।) 840 আসে 6-এর পরিবর্তে 7 দিয়ে গুণ করা থেকে, আর 620/700 কাছাকাছি হলেও গুণের নিয়ম একেবারেই অনুসরণ করে না।",
      ta: "அடுத்த உறுப்பைப் பெற ஒவ்வொரு உறுப்பும் அடுத்த எண்ணிக்கை எண்ணால் பெருக்கப்படுகிறது: 1×2=2, 2×3=6, 6×4=24, 24×5=120, எனவே 120×6=720. (இது ஒரு காரணிய (factorial) தொடர்: 1!, 2!, 3!, 4!, 5!, 6!.) 840 என்பது 6க்குப் பதிலாக 7ஆல் பெருக்கியதால் வருகிறது, 620/700 அருகில் இருந்தாலும் பெருக்கல் விதியை பின்பற்றவே இல்லை.",
    },
  },
  {
    key: "jnvst-2023-ma-08",
    year: 2023,
    sectionKey: "mental_ability",
    difficulty: "HARD",
    questionJson: {
      en: "In a certain code, 'SUN IS HOT' is written as 'TVO JT IPU'. How will 'MOON IS BIG' be written in that code?",
      hi: "एक निश्चित कोड में, 'SUN IS HOT' को 'TVO JT IPU' लिखा जाता है। उसी कोड में 'MOON IS BIG' कैसे लिखा जाएगा?",
      mr: "एका विशिष्ट कोडमध्ये, 'SUN IS HOT' हे 'TVO JT IPU' असे लिहिले जाते. त्याच कोडमध्ये 'MOON IS BIG' कसे लिहिले जाईल?",
      bn: "একটি নির্দিষ্ট কোডে, 'SUN IS HOT'-কে 'TVO JT IPU' লেখা হয়। একই কোডে 'MOON IS BIG' কীভাবে লেখা হবে?",
      ta: "ஒரு குறிப்பிட்ட குறியீட்டில், 'SUN IS HOT' என்பது 'TVO JT IPU' என்று எழுதப்படுகிறது. அதே குறியீட்டில் 'MOON IS BIG' எவ்வாறு எழுதப்படும்?",
    },
    optionsJson: [
      { en: "NPPO JT CJH", hi: "NPPO JT CJH", mr: "NPPO JT CJH", bn: "NPPO JT CJH", ta: "NPPO JT CJH" },
      { en: "NPOP JT CJH", hi: "NPOP JT CJH", mr: "NPOP JT CJH", bn: "NPOP JT CJH", ta: "NPOP JT CJH" },
      { en: "NPPO IS CJH", hi: "NPPO IS CJH", mr: "NPPO IS CJH", bn: "NPPO IS CJH", ta: "NPPO IS CJH" },
      { en: "MNNO JT CJH", hi: "MNNO JT CJH", mr: "MNNO JT CJH", bn: "MNNO JT CJH", ta: "MNNO JT CJH" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Every letter of every word is shifted forward by one place in the alphabet: S→T, U→V, N→O gives SUN→TVO; I→J, S→T gives IS→JT; H→I, O→P, T→U gives HOT→IPU — this matches the code given. Applying the same +1 shift to MOON IS BIG: M→N, O→P, O→P, N→O gives MOON→NPPO; I→J, S→T gives IS→JT; B→C, I→J, G→H gives BIG→CJH. So the full code is 'NPPO JT CJH'. 'NPOP JT CJH' swaps two middle letters of the first word, 'NPPO IS CJH' mistakenly leaves the short word IS unshifted, and 'MNNO JT CJH' mistakenly leaves the first word unshifted.",
      hi: "हर शब्द के हर अक्षर को वर्णमाला में एक स्थान आगे खिसकाया जाता है: S→T, U→V, N→O से SUN→TVO मिलता है; I→J, S→T से IS→JT मिलता है; H→I, O→P, T→U से HOT→IPU मिलता है — यह दिए गए कोड से मेल खाता है। MOON IS BIG पर वही +1 नियम लगाने पर: M→N, O→P, O→P, N→O से MOON→NPPO मिलता है; I→J, S→T से IS→JT मिलता है; B→C, I→J, G→H से BIG→CJH मिलता है। इसलिए पूरा कोड 'NPPO JT CJH' है। 'NPOP JT CJH' पहले शब्द के बीच के दो अक्षरों को अदल-बदल कर देता है, 'NPPO IS CJH' गलती से छोटे शब्द IS को नहीं खिसकाता, और 'MNNO JT CJH' गलती से पहले शब्द को नहीं खिसकाता।",
      mr: "प्रत्येक शब्दाचे प्रत्येक अक्षर वर्णमालेत एक स्थान पुढे सरकवले जाते: S→T, U→V, N→O वरून SUN→TVO मिळते; I→J, S→T वरून IS→JT मिळते; H→I, O→P, T→U वरून HOT→IPU मिळते — हे दिलेल्या कोडशी जुळते. MOON IS BIG वर तोच +1 नियम लावल्यास: M→N, O→P, O→P, N→O वरून MOON→NPPO मिळते; I→J, S→T वरून IS→JT मिळते; B→C, I→J, G→H वरून BIG→CJH मिळते. त्यामुळे संपूर्ण कोड 'NPPO JT CJH' आहे. 'NPOP JT CJH' पहिल्या शब्दातील मधली दोन अक्षरे अदलाबदल करते, 'NPPO IS CJH' चुकून लहान शब्द IS न सरकवता ठेवते, आणि 'MNNO JT CJH' चुकून पहिला शब्द न सरकवता ठेवते.",
      bn: "প্রতিটি শব্দের প্রতিটি অক্ষরকে বর্ণমালায় একটি স্থান এগিয়ে সরানো হয়: S→T, U→V, N→O থেকে SUN→TVO পাওয়া যায়; I→J, S→T থেকে IS→JT পাওয়া যায়; H→I, O→P, T→U থেকে HOT→IPU পাওয়া যায় — এটি প্রদত্ত কোডের সাথে মেলে। MOON IS BIG-এ একই +1 নিয়ম প্রয়োগ করলে: M→N, O→P, O→P, N→O থেকে MOON→NPPO পাওয়া যায়; I→J, S→T থেকে IS→JT পাওয়া যায়; B→C, I→J, G→H থেকে BIG→CJH পাওয়া যায়। তাই সম্পূর্ণ কোডটি হলো 'NPPO JT CJH'। 'NPOP JT CJH' প্রথম শব্দের মাঝের দুটি অক্ষর অদলবদল করে, 'NPPO IS CJH' ভুলবশত ছোট শব্দ IS-কে না সরিয়ে রাখে, এবং 'MNNO JT CJH' ভুলবশত প্রথম শব্দটি না সরিয়ে রাখে।",
      ta: "ஒவ்வொரு சொல்லின் ஒவ்வொரு எழுத்தும் அகரவரிசையில் ஒரு இடம் முன்னோக்கி நகர்த்தப்படுகிறது: S→T, U→V, N→O என்பதிலிருந்து SUN→TVO கிடைக்கிறது; I→J, S→T இலிருந்து IS→JT கிடைக்கிறது; H→I, O→P, T→U இலிருந்து HOT→IPU கிடைக்கிறது — இது கொடுக்கப்பட்ட குறியீட்டுடன் பொருந்துகிறது. MOON IS BIG-க்கு அதே +1 விதியைப் பயன்படுத்த: M→N, O→P, O→P, N→O இலிருந்து MOON→NPPO கிடைக்கிறது; I→J, S→T இலிருந்து IS→JT கிடைக்கிறது; B→C, I→J, G→H இலிருந்து BIG→CJH கிடைக்கிறது. எனவே முழு குறியீடும் 'NPPO JT CJH' ஆகும். 'NPOP JT CJH' முதல் சொல்லின் நடு இரண்டு எழுத்துகளை மாற்றுகிறது, 'NPPO IS CJH' தவறாக குறுகிய சொல் IS-ஐ நகர்த்தாமல் விடுகிறது, 'MNNO JT CJH' தவறாக முதல் சொல்லை நகர்த்தாமல் விடுகிறது.",
    },
  },

  // ── Arithmetic (4) ───────────────────────────────────────────────────
  {
    key: "jnvst-2023-ar-01",
    year: 2023,
    sectionKey: "arithmetic",
    difficulty: "EASY",
    questionJson: {
      en: "Use the Vedic shortcut for squaring a number ending in 5: 25² = ?",
      hi: "5 पर समाप्त होने वाली संख्या के वर्ग के लिए वैदिक शॉर्टकट का प्रयोग करें: 25² = ?",
      mr: "5 वर संपणाऱ्या संख्येच्या वर्गासाठी वैदिक शॉर्टकट वापरा: 25² = ?",
      bn: "5-এ শেষ হওয়া সংখ্যার বর্গের জন্য বৈদিক শর্টকাট ব্যবহার করুন: 25² = ?",
      ta: "5இல் முடிவடையும் எண்ணின் வர்க்கத்திற்கான வேத குறுக்குவழியைப் பயன்படுத்துங்கள்: 25² = ?",
    },
    optionsJson: [
      { en: "605", hi: "605", mr: "605", bn: "605", ta: "605" },
      { en: "615", hi: "615", mr: "615", bn: "615", ta: "615" },
      { en: "625", hi: "625", mr: "625", bn: "625", ta: "625" },
      { en: "635", hi: "635", mr: "635", bn: "635", ta: "635" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "For a number of the form 10a+5, the square is a×(a+1) followed by 25. Here 25=10×2+5, so a=2: a×(a+1)=2×3=6. Append 25 to get 625.",
      hi: "10a+5 रूप की संख्या के लिए, वर्ग a×(a+1) के बाद 25 लिखने से प्राप्त होता है। यहाँ 25=10×2+5, इसलिए a=2: a×(a+1)=2×3=6। 625 पाने के लिए 25 जोड़ें।",
      mr: "10a+5 रूपाच्या संख्येसाठी, वर्ग a×(a+1) नंतर 25 लिहून मिळतो. येथे 25=10×2+5, त्यामुळे a=2: a×(a+1)=2×3=6. 625 मिळवण्यासाठी 25 जोडा.",
      bn: "10a+5 আকারের সংখ্যার জন্য, বর্গ হলো a×(a+1)-এর পরে 25 বসিয়ে। এখানে 25=10×2+5, তাই a=2: a×(a+1)=2×3=6। 625 পেতে 25 যোগ করুন।",
      ta: "10a+5 வடிவ எண்ணுக்கு, வர்க்கம் a×(a+1) பிறகு 25 சேர்த்து கிடைக்கும். இங்கு 25=10×2+5, எனவே a=2: a×(a+1)=2×3=6. 625 பெற 25 சேர்க்கவும்.",
    },
  },
  {
    key: "jnvst-2023-ar-02",
    year: 2023,
    sectionKey: "arithmetic",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Use the Urdhva-Tiryagbhyam (vertically and crosswise) method to multiply: 23 × 42 = ?",
      hi: "गुणा करने के लिए ऊर्ध्व-तिर्यग्भ्याम् (ऊर्ध्वाधर एवं तिरछा) विधि का प्रयोग करें: 23 × 42 = ?",
      mr: "गुणाकारासाठी ऊर्ध्व-तिर्यग्भ्याम् (उभे व तिरपे) पद्धत वापरा: 23 × 42 = ?",
      bn: "গুণ করতে ঊর্ধ্ব-তির্যগ্ভ্যাম্ (উল্লম্ব ও তির্যক) পদ্ধতি ব্যবহার করুন: 23 × 42 = ?",
      ta: "பெருக்குவதற்கு ஊர்த்வ-திர்யக்பியாம் (செங்குத்து மற்றும் குறுக்கு) முறையைப் பயன்படுத்துங்கள்: 23 × 42 = ?",
    },
    optionsJson: [
      { en: "936", hi: "936", mr: "936", bn: "936", ta: "936" },
      { en: "956", hi: "956", mr: "956", bn: "956", ta: "956" },
      { en: "966", hi: "966", mr: "966", bn: "966", ta: "966" },
      { en: "976", hi: "976", mr: "976", bn: "976", ta: "976" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "For ab × cd (23 × 42, so a=2,b=3,c=4,d=2), work in three cross-multiplication steps. Vertical (units): b×d=3×2=6 → units digit 6, carry 0. Crosswise: a×d+b×c=2×2+3×4=4+12=16 → write 6, carry 1. Vertical (tens): a×c=2×4=8, plus the carried 1 = 9. Reading the digits gives 9, 6, 6 → 966.",
      hi: "ab × cd (23 × 42, तो a=2,b=3,c=4,d=2) के लिए, तीन क्रॉस-गुणा चरणों में काम करें। ऊर्ध्वाधर (इकाई): b×d=3×2=6 → इकाई अंक 6, कैरी 0। तिरछा: a×d+b×c=2×2+3×4=4+12=16 → 6 लिखें, कैरी 1। ऊर्ध्वाधर (दहाई): a×c=2×4=8, साथ में कैरी किया गया 1 = 9। अंकों को पढ़ने पर 9, 6, 6 → 966 मिलता है।",
      mr: "ab × cd (23 × 42, म्हणजे a=2,b=3,c=4,d=2) साठी, तीन क्रॉस-गुणाकार टप्प्यांत काम करा. उभे (एकक): b×d=3×2=6 → एकक अंक 6, कॅरी 0. तिरपे: a×d+b×c=2×2+3×4=4+12=16 → 6 लिहा, कॅरी 1. उभे (दशक): a×c=2×4=8, अधिक कॅरी केलेला 1 = 9. अंक वाचल्यास 9, 6, 6 → 966 मिळते.",
      bn: "ab × cd (23 × 42, তাই a=2,b=3,c=4,d=2) এর জন্য, তিনটি ক্রস-গুণন ধাপে কাজ করুন। উল্লম্ব (একক): b×d=3×2=6 → একক অঙ্ক 6, ক্যারি 0। তির্যক: a×d+b×c=2×2+3×4=4+12=16 → 6 লিখুন, ক্যারি 1। উল্লম্ব (দশক): a×c=2×4=8, সাথে বহন করা 1 = 9। অঙ্কগুলি পড়লে 9, 6, 6 → 966 পাওয়া যায়।",
      ta: "ab × cd (23 × 42, எனவே a=2,b=3,c=4,d=2) என்பதற்கு, மூன்று குறுக்கு-பெருக்கல் படிகளில் செயல்படவும். செங்குத்து (ஒன்றுகள்): b×d=3×2=6 → ஒன்றுகள் இலக்கம் 6, கேரி 0. குறுக்கு: a×d+b×c=2×2+3×4=4+12=16 → 6 எழுதவும், கேரி 1. செங்குத்து (பத்துகள்): a×c=2×4=8, கேரி செய்யப்பட்ட 1உடன் = 9. இலக்கங்களைப் படிக்கும்போது 9, 6, 6 → 966 கிடைக்கிறது.",
    },
  },
  {
    key: "jnvst-2023-ar-03",
    year: 2023,
    sectionKey: "arithmetic",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Use the Vedic shortcut for squaring a number ending in 5: 45² = ?",
      hi: "5 पर समाप्त होने वाली संख्या के वर्ग के लिए वैदिक शॉर्टकट का प्रयोग करें: 45² = ?",
      mr: "5 वर संपणाऱ्या संख्येच्या वर्गासाठी वैदिक शॉर्टकट वापरा: 45² = ?",
      bn: "5-এ শেষ হওয়া সংখ্যার বর্গের জন্য বৈদিক শর্টকাট ব্যবহার করুন: 45² = ?",
      ta: "5இல் முடிவடையும் எண்ணின் வர்க்கத்திற்கான வேத குறுக்குவழியைப் பயன்படுத்துங்கள்: 45² = ?",
    },
    optionsJson: [
      { en: "2005", hi: "2005", mr: "2005", bn: "2005", ta: "2005" },
      { en: "2015", hi: "2015", mr: "2015", bn: "2015", ta: "2015" },
      { en: "2025", hi: "2025", mr: "2025", bn: "2025", ta: "2025" },
      { en: "2035", hi: "2035", mr: "2035", bn: "2035", ta: "2035" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "For a number of the form 10a+5, the square is a×(a+1) followed by 25. Here 45=10×4+5, so a=4: a×(a+1)=4×5=20. Append 25 to get 2025.",
      hi: "10a+5 रूप की संख्या के लिए, वर्ग a×(a+1) के बाद 25 लिखने से प्राप्त होता है। यहाँ 45=10×4+5, इसलिए a=4: a×(a+1)=4×5=20। 2025 पाने के लिए 25 जोड़ें।",
      mr: "10a+5 रूपाच्या संख्येसाठी, वर्ग a×(a+1) नंतर 25 लिहून मिळतो. येथे 45=10×4+5, त्यामुळे a=4: a×(a+1)=4×5=20. 2025 मिळवण्यासाठी 25 जोडा.",
      bn: "10a+5 আকারের সংখ্যার জন্য, বর্গ হলো a×(a+1)-এর পরে 25 বসিয়ে। এখানে 45=10×4+5, তাই a=4: a×(a+1)=4×5=20। 2025 পেতে 25 যোগ করুন।",
      ta: "10a+5 வடிவ எண்ணுக்கு, வர்க்கம் a×(a+1) பிறகு 25 சேர்த்து கிடைக்கும். இங்கு 45=10×4+5, எனவே a=4: a×(a+1)=4×5=20. 2025 பெற 25 சேர்க்கவும்.",
    },
  },
  {
    key: "jnvst-2023-ar-04",
    year: 2023,
    sectionKey: "arithmetic",
    difficulty: "HARD",
    questionJson: {
      en: "Use the Urdhva-Tiryagbhyam (vertically and crosswise) method to multiply: 67 × 89 = ?",
      hi: "गुणा करने के लिए ऊर्ध्व-तिर्यग्भ्याम् (ऊर्ध्वाधर एवं तिरछा) विधि का प्रयोग करें: 67 × 89 = ?",
      mr: "गुणाकारासाठी ऊर्ध्व-तिर्यग्भ्याम् (उभे व तिरपे) पद्धत वापरा: 67 × 89 = ?",
      bn: "গুণ করতে ঊর্ধ্ব-তির্যগ্ভ্যাম্ (উল্লম্ব ও তির্যক) পদ্ধতি ব্যবহার করুন: 67 × 89 = ?",
      ta: "பெருக்குவதற்கு ஊர்த்வ-திர்யக்பியாம் (செங்குத்து மற்றும் குறுக்கு) முறையைப் பயன்படுத்துங்கள்: 67 × 89 = ?",
    },
    optionsJson: [
      { en: "5943", hi: "5943", mr: "5943", bn: "5943", ta: "5943" },
      { en: "5953", hi: "5953", mr: "5953", bn: "5953", ta: "5953" },
      { en: "5963", hi: "5963", mr: "5963", bn: "5963", ta: "5963" },
      { en: "5973", hi: "5973", mr: "5973", bn: "5973", ta: "5973" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "For ab × cd (67 × 89, so a=6,b=7,c=8,d=9), work in three cross-multiplication steps, carrying between steps. Vertical (units): b×d=7×9=63 → write 3, carry 6. Crosswise: a×d+b×c=6×9+7×8=54+56=110, plus the carried 6 = 116 → write 6, carry 11. Vertical (tens): a×c=6×8=48, plus the carried 11 = 59 (written in full since there is no further step to carry into). Reading the digits gives 59, 6, 3 → 5963.",
      hi: "ab × cd (67 × 89, तो a=6,b=7,c=8,d=9) के लिए, तीन क्रॉस-गुणा चरणों में काम करें, चरणों के बीच कैरी करते हुए। ऊर्ध्वाधर (इकाई): b×d=7×9=63 → 3 लिखें, कैरी 6। तिरछा: a×d+b×c=6×9+7×8=54+56=110, साथ में कैरी किया गया 6 = 116 → 6 लिखें, कैरी 11। ऊर्ध्वाधर (दहाई): a×c=6×8=48, साथ में कैरी किया गया 11 = 59 (पूरा लिखें क्योंकि इसके आगे कैरी करने के लिए कोई चरण नहीं है)। अंकों को पढ़ने पर 59, 6, 3 → 5963 मिलता है।",
      mr: "ab × cd (67 × 89, म्हणजे a=6,b=7,c=8,d=9) साठी, तीन क्रॉस-गुणाकार टप्प्यांत काम करा, टप्प्यांदरम्यान कॅरी करत. उभे (एकक): b×d=7×9=63 → 3 लिहा, कॅरी 6. तिरपे: a×d+b×c=6×9+7×8=54+56=110, अधिक कॅरी केलेला 6 = 116 → 6 लिहा, कॅरी 11. उभे (दशक): a×c=6×8=48, अधिक कॅरी केलेला 11 = 59 (पूर्ण लिहा कारण पुढे कॅरी करण्यासाठी टप्पा नाही). अंक वाचल्यास 59, 6, 3 → 5963 मिळते.",
      bn: "ab × cd (67 × 89, তাই a=6,b=7,c=8,d=9) এর জন্য, তিনটি ক্রস-গুণন ধাপে কাজ করুন, ধাপগুলির মধ্যে ক্যারি করে। উল্লম্ব (একক): b×d=7×9=63 → 3 লিখুন, ক্যারি 6। তির্যক: a×d+b×c=6×9+7×8=54+56=110, সাথে বহন করা 6 = 116 → 6 লিখুন, ক্যারি 11। উল্লম্ব (দশক): a×c=6×8=48, সাথে বহন করা 11 = 59 (সম্পূর্ণ লিখুন কারণ এর পরে বহন করার মতো আর কোনো ধাপ নেই)। অঙ্কগুলি পড়লে 59, 6, 3 → 5963 পাওয়া যায়।",
      ta: "ab × cd (67 × 89, எனவே a=6,b=7,c=8,d=9) என்பதற்கு, மூன்று குறுக்கு-பெருக்கல் படிகளில், படிகளுக்கு இடையே கேரி செய்து செயல்படவும். செங்குத்து (ஒன்றுகள்): b×d=7×9=63 → 3 எழுதவும், கேரி 6. குறுக்கு: a×d+b×c=6×9+7×8=54+56=110, கேரி செய்யப்பட்ட 6உடன் = 116 → 6 எழுதவும், கேரி 11. செங்குத்து (பத்துகள்): a×c=6×8=48, கேரி செய்யப்பட்ட 11உடன் = 59 (இதற்குப் பிறகு கேரி செய்ய படி இல்லாததால் முழுமையாக எழுதவும்). இலக்கங்களைப் படிக்கும்போது 59, 6, 3 → 5963 கிடைக்கிறது.",
    },
  },

  // ── Language (4) ─────────────────────────────────────────────────────
  {
    key: "jnvst-2023-lang-01",
    year: 2023,
    sectionKey: "language",
    difficulty: "EASY",
    questionJson: {
      en: 'Fill in the blank: "She ___ to school every day."',
      hi: 'रिक्त स्थान भरें: "She ___ to school every day."',
      mr: 'रिकामी जागा भरा: "She ___ to school every day."',
      bn: 'শূন্যস্থান পূরণ করুন: "She ___ to school every day."',
      ta: 'வெற்றிடத்தை நிரப்பவும்: "She ___ to school every day."',
    },
    optionsJson: [
      { en: "go", hi: "go", mr: "go", bn: "go", ta: "go" },
      { en: "goes", hi: "goes", mr: "goes", bn: "goes", ta: "goes" },
      { en: "going", hi: "going", mr: "going", bn: "going", ta: "going" },
      { en: "gone", hi: "gone", mr: "gone", bn: "gone", ta: "gone" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The subject 'She' is third-person singular, and the sentence describes a habitual action ('every day'), so the simple present tense verb must take an -s/-es ending: 'goes'. 'Go' is used with I/you/we/they, not she; 'going' and 'gone' need a helping verb (is going / has gone) and cannot stand alone here.",
      hi: "विषय 'She' तृतीय पुरुष एकवचन है, और वाक्य एक अभ्यस्त क्रिया का वर्णन करता है ('every day'), इसलिए साधारण वर्तमान काल की क्रिया में -s/-es अंत होना चाहिए: 'goes'। 'Go' का प्रयोग I/you/we/they के साथ होता है, she के साथ नहीं; 'going' और 'gone' को एक सहायक क्रिया (is going / has gone) चाहिए और यहाँ अकेले खड़े नहीं हो सकते।",
      mr: "विषय 'She' तृतीय पुरुष एकवचनी आहे, आणि वाक्य एक सवयीची क्रिया दर्शवते ('every day'), त्यामुळे साध्या वर्तमानकाळाच्या क्रियापदाला -s/-es शेवट हवा: 'goes'. 'Go' चा वापर I/you/we/they सोबत होतो, she सोबत नाही; 'going' आणि 'gone' ला साहाय्यक क्रियापद (is going / has gone) लागते आणि येथे एकटे उभे राहू शकत नाहीत.",
      bn: "কর্তা 'She' তৃতীয় পুরুষ একবচন, এবং বাক্যটি একটি অভ্যাসগত ক্রিয়া বর্ণনা করছে ('every day'), তাই সাধারণ বর্তমান কালের ক্রিয়াপদে -s/-es যুক্ত হতে হবে: 'goes'। 'Go' ব্যবহৃত হয় I/you/we/they-এর সাথে, she-এর সাথে নয়; 'going' এবং 'gone'-এর একটি সহায়ক ক্রিয়া (is going / has gone) প্রয়োজন এবং এখানে একা দাঁড়াতে পারে না।",
      ta: "'She' என்ற எழுவாய் மூன்றாம் இடம் ஒருமை, மேலும் இந்த வாக்கியம் ஒரு பழக்கமான செயலை விவரிக்கிறது ('every day'), எனவே எளிய நிகழ்கால வினைச்சொல் -s/-es முடிவைப் பெற வேண்டும்: 'goes'. 'Go' என்பது I/you/we/they உடன் பயன்படுத்தப்படுகிறது, she உடன் அல்ல; 'going' மற்றும் 'gone' ஆகியவற்றிற்கு ஒரு துணை வினை (is going / has gone) தேவை, இங்கே தனியாக நிற்க முடியாது.",
    },
  },
  {
    key: "jnvst-2023-lang-02",
    year: 2023,
    sectionKey: "language",
    difficulty: "EASY",
    questionJson: {
      en: 'Choose the correct plural form of "Mouse":',
      hi: '"Mouse" का सही बहुवचन रूप चुनें:',
      mr: '"Mouse" चे योग्य अनेकवचन रूप निवडा:',
      bn: '"Mouse"-এর সঠিক বহুবচন রূপ নির্বাচন করুন:',
      ta: '"Mouse" இன் சரியான பன்மை வடிவத்தைத் தேர்ந்தெடுக்கவும்:',
    },
    optionsJson: [
      { en: "Mouses", hi: "Mouses", mr: "Mouses", bn: "Mouses", ta: "Mouses" },
      { en: "Mice", hi: "Mice", mr: "Mice", bn: "Mice", ta: "Mice" },
      { en: "Mouse", hi: "Mouse", mr: "Mouse", bn: "Mouse", ta: "Mouse" },
      { en: "Miced", hi: "Miced", mr: "Miced", bn: "Miced", ta: "Miced" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "'Mouse' has an irregular plural formed by changing the vowel sound: 'Mice', not by adding '-s' or '-es'. 'Mouses' and 'Miced' apply the regular rule incorrectly, and 'Mouse' is simply the unchanged singular form.",
      hi: "'Mouse' का अनियमित बहुवचन स्वर ध्वनि बदलकर बनता है: 'Mice', न कि '-s' या '-es' जोड़कर। 'Mouses' और 'Miced' नियमित नियम को गलत तरीके से लागू करते हैं, और 'Mouse' केवल अपरिवर्तित एकवचन रूप है।",
      mr: "'Mouse' चे अनियमित अनेकवचन स्वर ध्वनी बदलून तयार होते: 'Mice', '-s' किंवा '-es' जोडून नाही. 'Mouses' आणि 'Miced' नियमित नियम चुकीच्या पद्धतीने लागू करतात, आणि 'Mouse' हे फक्त न बदललेले एकवचन रूप आहे.",
      bn: "'Mouse'-এর অনিয়মিত বহুবচন স্বরধ্বনি পরিবর্তন করে গঠিত হয়: 'Mice', '-s' বা '-es' যোগ করে নয়। 'Mouses' এবং 'Miced' নিয়মিত নিয়মটি ভুলভাবে প্রয়োগ করে, এবং 'Mouse' কেবল অপরিবর্তিত একবচন রূপ।",
      ta: "'Mouse' இன் ஒழுங்கற்ற பன்மை உயிர் ஒலியை மாற்றுவதன் மூலம் உருவாகிறது: 'Mice', '-s' அல்லது '-es' சேர்த்து அல்ல. 'Mouses' மற்றும் 'Miced' ஆகியவை வழக்கமான விதியை தவறாகப் பயன்படுத்துகின்றன, 'Mouse' என்பது மாறாத ஒருமை வடிவம் மட்டுமே.",
    },
  },
  {
    key: "jnvst-2023-lang-03",
    year: 2023,
    sectionKey: "language",
    difficulty: "MEDIUM",
    questionJson: {
      en: 'Choose the antonym (opposite) of "Brave":',
      hi: '"Brave" का विलोम (विपरीतार्थक) शब्द चुनें:',
      mr: '"Brave" चा विरुद्धार्थी शब्द निवडा:',
      bn: '"Brave"-এর বিপরীতার্থক শব্দটি নির্বাচন করুন:',
      ta: '"Brave" இன் எதிர்ச்சொல்லைத் தேர்ந்தெடுக்கவும்:',
    },
    optionsJson: [
      { en: "Courageous", hi: "Courageous", mr: "Courageous", bn: "Courageous", ta: "Courageous" },
      { en: "Cowardly", hi: "Cowardly", mr: "Cowardly", bn: "Cowardly", ta: "Cowardly" },
      { en: "Bold", hi: "Bold", mr: "Bold", bn: "Bold", ta: "Bold" },
      { en: "Fearless", hi: "Fearless", mr: "Fearless", bn: "Fearless", ta: "Fearless" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "'Brave' means having courage. Its opposite is 'Cowardly' (lacking courage, afraid to face danger). 'Courageous', 'Bold', and 'Fearless' are all synonyms of 'Brave', not opposites — this is a common trap where students pick a related word instead of a true opposite.",
      hi: "'Brave' का अर्थ है साहसी होना। इसका विपरीत 'Cowardly' (साहस की कमी, खतरे का सामना करने से डरना) है। 'Courageous', 'Bold' और 'Fearless' सभी 'Brave' के पर्यायवाची हैं, विपरीतार्थक नहीं — यह एक सामान्य जाल है जहाँ छात्र सच्चे विपरीतार्थक की बजाय संबंधित शब्द चुन लेते हैं।",
      mr: "'Brave' म्हणजे धैर्यवान असणे. त्याचा विरुद्धार्थी शब्द 'Cowardly' (धैर्याचा अभाव, धोक्याला सामोरे जाण्यास घाबरणे) आहे. 'Courageous', 'Bold' आणि 'Fearless' हे सर्व 'Brave' चे समानार्थी शब्द आहेत, विरुद्धार्थी नाहीत — हा एक सामान्य सापळा आहे जिथे विद्यार्थी खऱ्या विरुद्धार्थी शब्दाऐवजी संबंधित शब्द निवडतात.",
      bn: "'Brave' মানে সাহসী হওয়া। এর বিপরীত হলো 'Cowardly' (সাহসের অভাব, বিপদের সম্মুখীন হতে ভয় পাওয়া)। 'Courageous', 'Bold' এবং 'Fearless' সবই 'Brave'-এর সমার্থক শব্দ, বিপরীতার্থক নয় — এটি একটি সাধারণ ফাঁদ যেখানে শিক্ষার্থীরা প্রকৃত বিপরীত শব্দের বদলে সম্পর্কিত শব্দ বেছে নেয়।",
      ta: "'Brave' என்றால் தைரியம் கொண்டிருத்தல். இதன் எதிர்ச்சொல் 'Cowardly' (தைரியமின்மை, ஆபத்தை எதிர்கொள்ள பயப்படுதல்). 'Courageous', 'Bold', 'Fearless' ஆகியவை அனைத்தும் 'Brave' இன் ஒத்த சொற்களே, எதிர்ச்சொற்கள் அல்ல — இது மாணவர்கள் உண்மையான எதிர்ச்சொல்லுக்குப் பதிலாக தொடர்புடைய சொல்லைத் தேர்ந்தெடுக்கும் ஒரு பொதுவான பொறியாகும்.",
    },
  },
  {
    key: "jnvst-2023-lang-04",
    year: 2023,
    sectionKey: "language",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Choose the correctly spelled word:",
      hi: "सही वर्तनी वाला शब्द चुनें:",
      mr: "योग्य शब्दलेखन असलेला शब्द निवडा:",
      bn: "সঠিক বানানের শব্দটি নির্বাচন করুন:",
      ta: "சரியான எழுத்துப்பிழையற்ற சொல்லைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Recieve", hi: "Recieve", mr: "Recieve", bn: "Recieve", ta: "Recieve" },
      { en: "Receive", hi: "Receive", mr: "Receive", bn: "Receive", ta: "Receive" },
      { en: "Receeve", hi: "Receeve", mr: "Receeve", bn: "Receeve", ta: "Receeve" },
      { en: "Receve", hi: "Receve", mr: "Receve", bn: "Receve", ta: "Receve" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The correct spelling is 'Receive'. It follows the rule 'i before e, except after c' — since the word contains 'c', the 'e' comes before the 'i': 'ceive'. 'Recieve' breaks this rule by reversing i and e, while 'Receeve' and 'Receve' are simply misspelled forms of the same word.",
      hi: "सही वर्तनी 'Receive' है। यह नियम का पालन करता है 'i before e, except after c' — चूंकि शब्द में 'c' है, इसलिए 'e', 'i' से पहले आता है: 'ceive'। 'Recieve' i और e को उलट कर इस नियम को तोड़ता है, जबकि 'Receeve' और 'Receve' उसी शब्द की केवल गलत वर्तनी वाली रूप हैं।",
      mr: "योग्य शब्दलेखन 'Receive' आहे. हे नियमाचे पालन करते 'i before e, except after c' — कारण शब्दात 'c' आहे, त्यामुळे 'e' हे 'i' आधी येते: 'ceive'. 'Recieve' i आणि e उलटे करून हा नियम मोडते, तर 'Receeve' आणि 'Receve' हे त्याच शब्दाचे फक्त चुकीच्या शब्दलेखनाचे रूप आहेत.",
      bn: "সঠিক বানান হলো 'Receive'। এটি নিয়ম অনুসরণ করে 'i before e, except after c' — যেহেতু শব্দটিতে 'c' আছে, তাই 'e', 'i'-এর আগে আসে: 'ceive'। 'Recieve' i এবং e উল্টে দিয়ে এই নিয়ম ভাঙে, আর 'Receeve' এবং 'Receve' একই শব্দের নিছক ভুল বানানের রূপ।",
      ta: "சரியான எழுத்துப்பிழை 'Receive' ஆகும். இது 'i before e, except after c' என்ற விதியைப் பின்பற்றுகிறது — சொல்லில் 'c' இருப்பதால், 'e', 'i'க்கு முன் வருகிறது: 'ceive'. 'Recieve' i மற்றும் e ஐ மாற்றி இந்த விதியை மீறுகிறது, 'Receeve' மற்றும் 'Receve' ஆகியவை அதே சொல்லின் தவறான எழுத்துப்பிழை வடிவங்கள் மட்டுமே.",
    },
  },
];
