import type { PyqSeedItem } from "./types";

// Original JNVST Class 6 practice questions, cohort-labelled "2021" as one of
// five parallel year-batches (2021-2025) feeding the shared PYQ bank. These
// are NOT reproductions of any real/official NVS past paper — there is no
// verified, licensed source for that in this project. They are freshly
// authored questions modeled on the known JNVST section/difficulty pattern,
// in the same house style as packages/db/prisma/seed.ts.

export const posts: PyqSeedItem[] = [
  // ---------------------------------------------------------------------
  // Mental Ability (8 items): number series, letter series, classification,
  // analogy, coding-decoding, pattern completion. 3 EASY, 3 MEDIUM, 2 HARD.
  // ---------------------------------------------------------------------
  {
    key: "jnvst-2021-ma-01",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Find the missing number: 7, 14, 21, 28, ?",
      hi: "लुप्त संख्या ज्ञात करें: 7, 14, 21, 28, ?",
      mr: "लुप्त संख्या शोधा: 7, 14, 21, 28, ?",
      bn: "অনুপস্থিত সংখ্যাটি খুঁজুন: 7, 14, 21, 28, ?",
      ta: "விடுபட்ட எண்ணைக் கண்டறியவும்: 7, 14, 21, 28, ?",
    },
    optionsJson: [
      { en: "32", hi: "32", mr: "32", bn: "32", ta: "32" },
      { en: "35", hi: "35", mr: "35", bn: "35", ta: "35" },
      { en: "36", hi: "36", mr: "36", bn: "36", ta: "36" },
      { en: "42", hi: "42", mr: "42", bn: "42", ta: "42" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "These are multiples of 7: 7×1=7, 7×2=14, 7×3=21, 7×4=28, so 7×5=35.",
      hi: "ये 7 के गुणज हैं: 7×1=7, 7×2=14, 7×3=21, 7×4=28, इसलिए 7×5=35।",
      mr: "हे 7 चे पट आहेत: 7×1=7, 7×2=14, 7×3=21, 7×4=28, म्हणून 7×5=35.",
      bn: "এগুলি 7-এর গুণিতক: 7×1=7, 7×2=14, 7×3=21, 7×4=28, তাই 7×5=35।",
      ta: "இவை 7-இன் மடங்குகள்: 7×1=7, 7×2=14, 7×3=21, 7×4=28, எனவே 7×5=35.",
    },
  },
  {
    key: "jnvst-2021-ma-02",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Find the missing letter: B, D, F, H, ?",
      hi: "लुप्त अक्षर ज्ञात करें: B, D, F, H, ?",
      mr: "लुप्त अक्षर शोधा: B, D, F, H, ?",
      bn: "অনুপস্থিত অক্ষরটি খুঁজুন: B, D, F, H, ?",
      ta: "விடுபட்ட எழுத்தைக் கண்டறியவும்: B, D, F, H, ?",
    },
    optionsJson: [
      { en: "I", hi: "I", mr: "I", bn: "I", ta: "I" },
      { en: "J", hi: "J", mr: "J", bn: "J", ta: "J" },
      { en: "K", hi: "K", mr: "K", bn: "K", ta: "K" },
      { en: "L", hi: "L", mr: "L", bn: "L", ta: "L" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The series skips one letter each time (+2): B→D→F→H→J.",
      hi: "यह श्रृंखला हर बार एक अक्षर छोड़ती है (+2): B→D→F→H→J।",
      mr: "ही मालिका दर वेळी एक अक्षर वगळते (+2): B→D→F→H→J.",
      bn: "এই ধারাটি প্রতিবার একটি অক্ষর বাদ দেয় (+2): B→D→F→H→J।",
      ta: "இந்த வரிசை ஒவ்வொரு முறையும் ஒரு எழுத்தைத் தவிர்க்கிறது (+2): B→D→F→H→J.",
    },
  },
  {
    key: "jnvst-2021-ma-03",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Which one does not belong with the others: Rose, Lotus, Jasmine, Mango?",
      hi: "इनमें से कौन-सा अन्य से मेल नहीं खाता: गुलाब, कमल, चमेली, आम?",
      mr: "यापैकी कोणता इतरांशी जुळत नाही: गुलाब, कमळ, चमेली, आंबा?",
      bn: "এর মধ্যে কোনটি অন্যদের সাথে মেলে না: গোলাপ, পদ্ম, জুঁই, আম?",
      ta: "இவற்றில் எது மற்றவற்றுடன் பொருந்தவில்லை: ரோஜா, தாமரை, மல்லிகை, மாம்பழம்?",
    },
    optionsJson: [
      { en: "Rose", hi: "गुलाब", mr: "गुलाब", bn: "গোলাপ", ta: "ரோஜா" },
      { en: "Lotus", hi: "कमल", mr: "कमळ", bn: "পদ্ম", ta: "தாமரை" },
      { en: "Jasmine", hi: "चमेली", mr: "चमेली", bn: "জুঁই", ta: "மல்லிகை" },
      { en: "Mango", hi: "आम", mr: "आंबा", bn: "আম", ta: "மாம்பழம்" },
    ],
    correctAnswer: 3,
    explanation: {
      en: "Rose, Lotus, and Jasmine are flowers; Mango is a fruit.",
      hi: "गुलाब, कमल और चमेली फूल हैं; आम एक फल है।",
      mr: "गुलाब, कमळ आणि चमेली ही फुले आहेत; आंबा हे फळ आहे.",
      bn: "গোলাপ, পদ্ম এবং জুঁই ফুল; আম একটি ফল।",
      ta: "ரோஜா, தாமரை மற்றும் மல்லிகை ஆகியவை பூக்கள்; மாம்பழம் ஒரு பழம்.",
    },
  },
  {
    key: "jnvst-2021-ma-04",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Doctor is related to Hospital in the same way as Teacher is related to ?",
      hi: "डॉक्टर का अस्पताल से वही संबंध है जो अध्यापक का ? से है।",
      mr: "डॉक्टरचा रुग्णालयाशी जसा संबंध आहे, तसाच शिक्षकाचा कशाशी आहे?",
      bn: "ডাক্তারের সাথে হাসপাতালের যে সম্পর্ক, শিক্ষকের সাথে তার সম্পর্ক কীসের সাথে?",
      ta: "மருத்துவருக்கும் மருத்துவமனைக்கும் உள்ள தொடர்பு போலவே ஆசிரியருக்கும் எதற்கும் தொடர்பு உள்ளது?",
    },
    optionsJson: [
      { en: "School", hi: "विद्यालय", mr: "शाळा", bn: "বিদ্যালয়", ta: "பள்ளி" },
      { en: "Book", hi: "किताब", mr: "पुस्तक", bn: "বই", ta: "புத்தகம்" },
      { en: "Student", hi: "छात्र", mr: "विद्यार्थी", bn: "ছাত্র", ta: "மாணவர்" },
      { en: "Classroom", hi: "कक्षा", mr: "वर्गखोली", bn: "শ্রেণিকক্ষ", ta: "வகுப்பறை" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "A Doctor works at a Hospital; similarly, a Teacher works at a School.",
      hi: "एक डॉक्टर अस्पताल में काम करता है; उसी प्रकार, एक अध्यापक विद्यालय में काम करता है।",
      mr: "डॉक्टर रुग्णालयात काम करतो; त्याचप्रमाणे, शिक्षक शाळेत काम करतो.",
      bn: "একজন ডাক্তার হাসপাতালে কাজ করেন; একইভাবে, একজন শিক্ষক বিদ্যালয়ে কাজ করেন।",
      ta: "ஒரு மருத்துவர் மருத்துவமனையில் பணிபுரிகிறார்; அதேபோல், ஒரு ஆசிரியர் பள்ளியில் பணிபுரிகிறார்.",
    },
  },
  {
    key: "jnvst-2021-ma-05",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "If, in a certain code, CAT is written as DBU, how is DOG written in the same code?",
      hi: "यदि एक निश्चित कूट भाषा में CAT को DBU लिखा जाता है, तो उसी कूट में DOG को कैसे लिखा जाएगा?",
      mr: "जर एका विशिष्ट सांकेतिक भाषेत CAT हे DBU असे लिहितात, तर त्याच सांकेतिक भाषेत DOG कसे लिहिले जाईल?",
      bn: "যদি একটি নির্দিষ্ট কোড ভাষায় CAT-কে DBU লেখা হয়, তবে একই কোডে DOG কীভাবে লেখা হবে?",
      ta: "ஒரு குறியீட்டு மொழியில் CAT என்பது DBU என எழுதப்பட்டால், அதே குறியீட்டில் DOG எவ்வாறு எழுதப்படும்?",
    },
    optionsJson: [
      { en: "EPH", hi: "EPH", mr: "EPH", bn: "EPH", ta: "EPH" },
      { en: "EPG", hi: "EPG", mr: "EPG", bn: "EPG", ta: "EPG" },
      { en: "FPH", hi: "FPH", mr: "FPH", bn: "FPH", ta: "FPH" },
      { en: "EOH", hi: "EOH", mr: "EOH", bn: "EOH", ta: "EOH" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Each letter is shifted forward by one place in the alphabet: C→D, A→B, T→U. Applying the same rule to DOG: D→E, O→P, G→H, giving EPH. Options EPG, FPH, and EOH each shift only some letters correctly, not all three.",
      hi: "प्रत्येक अक्षर को वर्णमाला में एक स्थान आगे खिसकाया जाता है: C→D, A→B, T→U। यही नियम DOG पर लागू करने पर: D→E, O→P, G→H, जिससे EPH प्राप्त होता है। विकल्प EPG, FPH और EOH में केवल कुछ अक्षर ही सही ढंग से खिसके हैं, तीनों नहीं।",
      mr: "प्रत्येक अक्षर वर्णमालेत एक स्थान पुढे सरकवले जाते: C→D, A→B, T→U. हाच नियम DOG ला लावल्यास: D→E, O→P, G→H, म्हणजे EPH मिळते. EPG, FPH आणि EOH या पर्यायांमध्ये फक्त काही अक्षरे बरोबर सरकवली आहेत, तिन्ही नाहीत.",
      bn: "প্রতিটি অক্ষরকে বর্ণমালায় একটি স্থান সামনে সরানো হয়েছে: C→D, A→B, T→U। একই নিয়ম DOG-এ প্রয়োগ করলে: D→E, O→P, G→H, ফলে EPH পাওয়া যায়। EPG, FPH এবং EOH বিকল্পগুলিতে কেবল কিছু অক্ষর সঠিকভাবে সরানো হয়েছে, তিনটিই নয়।",
      ta: "ஒவ்வொரு எழுத்தும் அகரவரிசையில் ஒரு இடம் முன்னோக்கி நகர்த்தப்படுகிறது: C→D, A→B, T→U. அதே விதியை DOG-க்குப் பயன்படுத்தும்போது: D→E, O→P, G→H, இதனால் EPH கிடைக்கிறது. EPG, FPH மற்றும் EOH ஆகிய தேர்வுகளில் சில எழுத்துகள் மட்டுமே சரியாக நகர்த்தப்பட்டுள்ளன, மூன்றும் இல்லை.",
    },
  },
  {
    key: "jnvst-2021-ma-06",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Find the missing number in the pattern: 2, 6, 12, 20, 30, ?",
      hi: "पैटर्न में लुप्त संख्या ज्ञात करें: 2, 6, 12, 20, 30, ?",
      mr: "पॅटर्नमधील लुप्त संख्या शोधा: 2, 6, 12, 20, 30, ?",
      bn: "প্যাটার্নে অনুপস্থিত সংখ্যাটি খুঁজুন: 2, 6, 12, 20, 30, ?",
      ta: "வடிவத்தில் விடுபட்ட எண்ணைக் கண்டறியவும்: 2, 6, 12, 20, 30, ?",
    },
    optionsJson: [
      { en: "40", hi: "40", mr: "40", bn: "40", ta: "40" },
      { en: "42", hi: "42", mr: "42", bn: "42", ta: "42" },
      { en: "36", hi: "36", mr: "36", bn: "36", ta: "36" },
      { en: "44", hi: "44", mr: "44", bn: "44", ta: "44" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "Each term is n×(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, so the next is 6×7=42.",
      hi: "प्रत्येक पद n×(n+1) है: 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, इसलिए अगला पद 6×7=42 है।",
      mr: "प्रत्येक पद n×(n+1) आहे: 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, म्हणून पुढील पद 6×7=42 आहे.",
      bn: "প্রতিটি পদ n×(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, তাই পরেরটি 6×7=42।",
      ta: "ஒவ்வொரு உறுப்பும் n×(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, எனவே அடுத்தது 6×7=42.",
    },
  },
  {
    key: "jnvst-2021-ma-07",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "HARD",
    questionJson: {
      en: "Find the missing number: 1, 1, 2, 3, 5, 8, 13, ?",
      hi: "लुप्त संख्या ज्ञात करें: 1, 1, 2, 3, 5, 8, 13, ?",
      mr: "लुप्त संख्या शोधा: 1, 1, 2, 3, 5, 8, 13, ?",
      bn: "অনুপস্থিত সংখ্যাটি খুঁজুন: 1, 1, 2, 3, 5, 8, 13, ?",
      ta: "விடுபட்ட எண்ணைக் கண்டறியவும்: 1, 1, 2, 3, 5, 8, 13, ?",
    },
    optionsJson: [
      { en: "18", hi: "18", mr: "18", bn: "18", ta: "18" },
      { en: "20", hi: "20", mr: "20", bn: "20", ta: "20" },
      { en: "21", hi: "21", mr: "21", bn: "21", ta: "21" },
      { en: "24", hi: "24", mr: "24", bn: "24", ta: "24" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "Each number is the sum of the two numbers before it: 5+8=13, so the next is 8+13=21. Option 18 wrongly adds 5+13, 20 is not the sum of any two consecutive terms, and 24 overshoots the pattern.",
      hi: "प्रत्येक संख्या अपने से पहले की दो संख्याओं का योग है: 5+8=13, इसलिए अगली संख्या 8+13=21 है। विकल्प 18 गलती से 5+13 जोड़ता है, 20 किन्हीं भी दो लगातार पदों का योग नहीं है, और 24 पैटर्न से आगे निकल जाता है।",
      mr: "प्रत्येक संख्या तिच्या आधीच्या दोन संख्यांची बेरीज आहे: 5+8=13, म्हणून पुढील संख्या 8+13=21 आहे. पर्याय 18 चुकीने 5+13 जोडतो, 20 ही कोणत्याही दोन सलग पदांची बेरीज नाही, आणि 24 पॅटर्नच्या पुढे जाते.",
      bn: "প্রতিটি সংখ্যা তার আগের দুটি সংখ্যার যোগফল: 5+8=13, তাই পরের সংখ্যাটি 8+13=21। বিকল্প 18 ভুলভাবে 5+13 যোগ করে, 20 কোনো দুটি ধারাবাহিক পদের যোগফল নয়, এবং 24 প্যাটার্নের চেয়ে বেশি।",
      ta: "ஒவ்வொரு எண்ணும் அதற்கு முந்தைய இரண்டு எண்களின் கூட்டுத்தொகை: 5+8=13, எனவே அடுத்த எண் 8+13=21. விருப்பம் 18 தவறாக 5+13ஐக் கூட்டுகிறது, 20 எந்த இரண்டு தொடர்ச்சியான உறுப்புகளின் கூட்டுத்தொகையும் இல்லை, மேலும் 24 வடிவத்தை மீறுகிறது.",
    },
  },
  {
    key: "jnvst-2021-ma-08",
    year: 2021,
    sectionKey: "mental_ability",
    difficulty: "HARD",
    questionJson: {
      en: "In a certain code, each letter is replaced by the letter that is the same number of places from the end of the alphabet (A↔Z, B↔Y, C↔X, and so on). If GOLD is written as TLOW in this code, how is SUN written?",
      hi: "एक निश्चित कूट भाषा में, प्रत्येक अक्षर को वर्णमाला के अंत से उतने ही स्थान दूर वाले अक्षर से बदला जाता है (A↔Z, B↔Y, C↔X, इत्यादि)। यदि इस कूट में GOLD को TLOW लिखा जाता है, तो SUN को कैसे लिखा जाएगा?",
      mr: "एका विशिष्ट सांकेतिक भाषेत, प्रत्येक अक्षर वर्णमालेच्या शेवटापासून तितक्याच अंतरावरील अक्षराने बदलले जाते (A↔Z, B↔Y, C↔X, इत्यादी). जर या कूटात GOLD हे TLOW असे लिहितात, तर SUN कसे लिहिले जाईल?",
      bn: "একটি নির্দিষ্ট কোডে, প্রতিটি অক্ষরকে বর্ণমালার শেষ থেকে একই সংখ্যক স্থান দূরের অক্ষর দিয়ে প্রতিস্থাপিত করা হয় (A↔Z, B↔Y, C↔X, ইত্যাদি)। যদি এই কোডে GOLD-কে TLOW লেখা হয়, তবে SUN কীভাবে লেখা হবে?",
      ta: "ஒரு குறியீட்டில், ஒவ்வொரு எழுத்தும் அகரவரிசையின் முடிவிலிருந்து அதே எண்ணிக்கையிலான இடங்களில் உள்ள எழுத்தால் மாற்றப்படுகிறது (A↔Z, B↔Y, C↔X, மற்றும் பல). இந்தக் குறியீட்டில் GOLD என்பது TLOW எனில், SUN எவ்வாறு எழுதப்படும்?",
    },
    optionsJson: [
      { en: "HFM", hi: "HFM", mr: "HFM", bn: "HFM", ta: "HFM" },
      { en: "GFM", hi: "GFM", mr: "GFM", bn: "GFM", ta: "GFM" },
      { en: "HFN", hi: "HFN", mr: "HFN", bn: "HFN", ta: "HFN" },
      { en: "IFM", hi: "IFM", mr: "IFM", bn: "IFM", ta: "IFM" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Mirror mapping: position p pairs with position (27-p). S(19th)→H(8th), U(21st)→F(6th), N(14th)→M(13th), giving HFM. Option GFM shifts the first letter wrong, HFN shifts the last letter wrong, and IFM shifts the first letter wrong.",
      hi: "दर्पण मानचित्रण: स्थान p, स्थान (27-p) से जुड़ता है। S(19वां)→H(8वां), U(21वां)→F(6ठा), N(14वां)→M(13वां), जिससे HFM प्राप्त होता है। विकल्प GFM में पहला अक्षर गलत है, HFN में अंतिम अक्षर गलत है, और IFM में पहला अक्षर गलत है।",
      mr: "आरसा मांडणी: स्थान p, स्थान (27-p) शी जुळते. S(19वे)→H(8वे), U(21वे)→F(6वे), N(14वे)→M(13वे), म्हणजे HFM मिळते. GFM मध्ये पहिले अक्षर चुकीचे आहे, HFN मध्ये शेवटचे अक्षर चुकीचे आहे, आणि IFM मध्ये पहिले अक्षर चुकीचे आहे.",
      bn: "আয়না ম্যাপিং: স্থান p, স্থান (27-p)-এর সাথে জোড়া হয়। S(19তম)→H(8ম), U(21তম)→F(6ষ্ঠ), N(14তম)→M(13তম), ফলে HFM পাওয়া যায়। বিকল্প GFM-এ প্রথম অক্ষরটি ভুল, HFN-এ শেষ অক্ষরটি ভুল, এবং IFM-এ প্রথম অক্ষরটি ভুল।",
      ta: "கண்ணாடி பொருத்தம்: இடம் p, இடம் (27-p) உடன் இணைகிறது. S(19வது)→H(8வது), U(21வது)→F(6வது), N(14வது)→M(13வது), இதனால் HFM கிடைக்கிறது. GFM இல் முதல் எழுத்து தவறு, HFN இல் கடைசி எழுத்து தவறு, மேலும் IFM இல் முதல் எழுத்து தவறு.",
    },
  },

  // ---------------------------------------------------------------------
  // Arithmetic (4 items): Nikhilam sutra (base multiplication) and the
  // "square of a number ending in 5" shortcut. 1 EASY, 2 MEDIUM, 1 HARD.
  // ---------------------------------------------------------------------
  {
    key: "jnvst-2021-ar-01",
    year: 2021,
    sectionKey: "arithmetic",
    difficulty: "EASY",
    questionJson: {
      en: "Calculate quickly using the 'square of a number ending in 5' shortcut: 25² = ?",
      hi: "'5 पर समाप्त होने वाली संख्या का वर्ग' शॉर्टकट का उपयोग करके शीघ्र गणना करें: 25² = ?",
      mr: "'5 ने संपणाऱ्या संख्येचा वर्ग' या शॉर्टकटचा वापर करून शीघ्र गणना करा: 25² = ?",
      bn: "'5-এ শেষ হওয়া সংখ্যার বর্গ' শর্টকাট ব্যবহার করে দ্রুত হিসাব করুন: 25² = ?",
      ta: "'5-இல் முடியும் எண்ணின் வர்க்கம்' குறுக்குவழியைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 25² = ?",
    },
    optionsJson: [
      { en: "525", hi: "525", mr: "525", bn: "525", ta: "525" },
      { en: "625", hi: "625", mr: "625", bn: "625", ta: "625" },
      { en: "725", hi: "725", mr: "725", bn: "725", ta: "725" },
      { en: "615", hi: "615", mr: "615", bn: "615", ta: "615" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "For a number 10a+5, the square is a×(a+1) followed by 25. Here a=2: 2×3=6, then append 25 → 625.",
      hi: "10a+5 रूप की संख्या के लिए, वर्ग a×(a+1) के बाद 25 जोड़कर बनता है। यहाँ a=2: 2×3=6, फिर 25 जोड़ें → 625।",
      mr: "10a+5 स्वरूपाच्या संख्येसाठी, वर्ग म्हणजे a×(a+1) नंतर 25 जोडून मिळतो. येथे a=2: 2×3=6, नंतर 25 जोडा → 625.",
      bn: "10a+5 আকারের সংখ্যার জন্য, বর্গটি a×(a+1)-এর পরে 25 যোগ করে পাওয়া যায়। এখানে a=2: 2×3=6, তারপর 25 যোগ করুন → 625।",
      ta: "10a+5 வடிவ எண்ணிற்கு, வர்க்கம் a×(a+1) க்குப் பிறகு 25 ஐ இணைப்பதன் மூலம் கிடைக்கும். இங்கே a=2: 2×3=6, பின்னர் 25 ஐ இணைக்கவும் → 625.",
    },
  },
  {
    key: "jnvst-2021-ar-02",
    year: 2021,
    sectionKey: "arithmetic",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Use the Nikhilam sutra to calculate quickly: 96 × 94 = ?",
      hi: "निखिलम् सूत्र का उपयोग करके शीघ्र गणना करें: 96 × 94 = ?",
      mr: "निखिलम् सूत्राचा वापर करून शीघ्र गणना करा: 96 × 94 = ?",
      bn: "নিখিলম সূত্র ব্যবহার করে দ্রুত হিসাব করুন: 96 × 94 = ?",
      ta: "நிகிலம் சூத்திரத்தைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 96 × 94 = ?",
    },
    optionsJson: [
      { en: "8924", hi: "8924", mr: "8924", bn: "8924", ta: "8924" },
      { en: "9024", hi: "9024", mr: "9024", bn: "9024", ta: "9024" },
      { en: "9124", hi: "9124", mr: "9124", bn: "9124", ta: "9124" },
      { en: "9034", hi: "9034", mr: "9034", bn: "9034", ta: "9034" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "Base 100, deviations -4 and -6: (96-6)×100 + (-4×-6) = 9000+24 = 9024.",
      hi: "आधार 100, विचलन -4 और -6: (96-6)×100 + (-4×-6) = 9000+24 = 9024।",
      mr: "आधार 100, विचलन -4 आणि -6: (96-6)×100 + (-4×-6) = 9000+24 = 9024.",
      bn: "ভিত্তি 100, বিচ্যুতি -4 এবং -6: (96-6)×100 + (-4×-6) = 9000+24 = 9024।",
      ta: "அடிப்படை 100, விலகல்கள் -4 மற்றும் -6: (96-6)×100 + (-4×-6) = 9000+24 = 9024.",
    },
  },
  {
    key: "jnvst-2021-ar-03",
    year: 2021,
    sectionKey: "arithmetic",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Calculate quickly using the 'square of a number ending in 5' shortcut: 85² = ?",
      hi: "'5 पर समाप्त होने वाली संख्या का वर्ग' शॉर्टकट का उपयोग करके शीघ्र गणना करें: 85² = ?",
      mr: "'5 ने संपणाऱ्या संख्येचा वर्ग' या शॉर्टकटचा वापर करून शीघ्र गणना करा: 85² = ?",
      bn: "'5-এ শেষ হওয়া সংখ্যার বর্গ' শর্টকাট ব্যবহার করে দ্রুত হিসাব করুন: 85² = ?",
      ta: "'5-இல் முடியும் எண்ணின் வர்க்கம்' குறுக்குவழியைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 85² = ?",
    },
    optionsJson: [
      { en: "7025", hi: "7025", mr: "7025", bn: "7025", ta: "7025" },
      { en: "7125", hi: "7125", mr: "7125", bn: "7125", ta: "7125" },
      { en: "7225", hi: "7225", mr: "7225", bn: "7225", ta: "7225" },
      { en: "7325", hi: "7325", mr: "7325", bn: "7325", ta: "7325" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "Here a=8: 8×9=72, then append 25 → 7225.",
      hi: "यहाँ a=8: 8×9=72, फिर 25 जोड़ें → 7225।",
      mr: "येथे a=8: 8×9=72, नंतर 25 जोडा → 7225.",
      bn: "এখানে a=8: 8×9=72, তারপর 25 যোগ করুন → 7225।",
      ta: "இங்கே a=8: 8×9=72, பின்னர் 25 ஐ இணைக்கவும் → 7225.",
    },
  },
  {
    key: "jnvst-2021-ar-04",
    year: 2021,
    sectionKey: "arithmetic",
    difficulty: "HARD",
    questionJson: {
      en: "Use the Nikhilam sutra to calculate quickly: 998 × 996 = ?",
      hi: "निखिलम् सूत्र का उपयोग करके शीघ्र गणना करें: 998 × 996 = ?",
      mr: "निखिलम् सूत्राचा वापर करून शीघ्र गणना करा: 998 × 996 = ?",
      bn: "নিখিলম সূত্র ব্যবহার করে দ্রুত হিসাব করুন: 998 × 996 = ?",
      ta: "நிகிலம் சூத்திரத்தைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 998 × 996 = ?",
    },
    optionsJson: [
      { en: "994008", hi: "994008", mr: "994008", bn: "994008", ta: "994008" },
      { en: "993008", hi: "993008", mr: "993008", bn: "993008", ta: "993008" },
      { en: "994108", hi: "994108", mr: "994108", bn: "994108", ta: "994108" },
      { en: "992008", hi: "992008", mr: "992008", bn: "992008", ta: "992008" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Base 1000, deviations -2 and -4: (998-4)×1000 + (-2×-4) = 994000+8 = 994008.",
      hi: "आधार 1000, विचलन -2 और -4: (998-4)×1000 + (-2×-4) = 994000+8 = 994008।",
      mr: "आधार 1000, विचलन -2 आणि -4: (998-4)×1000 + (-2×-4) = 994000+8 = 994008.",
      bn: "ভিত্তি 1000, বিচ্যুতি -2 এবং -4: (998-4)×1000 + (-2×-4) = 994000+8 = 994008।",
      ta: "அடிப்படை 1000, விலகல்கள் -2 மற்றும் -4: (998-4)×1000 + (-2×-4) = 994000+8 = 994008.",
    },
  },

  // ---------------------------------------------------------------------
  // Language (4 items): basic English grammar/vocabulary. 2 EASY, 2 MEDIUM.
  // ---------------------------------------------------------------------
  {
    key: "jnvst-2021-lang-01",
    year: 2021,
    sectionKey: "language",
    difficulty: "EASY",
    questionJson: {
      en: 'Fill in the blank: "She ___ to school every day."',
      hi: 'रिक्त स्थान भरें: "She ___ to school every day."',
      mr: 'रिकामी जागा भरा: "She ___ to school every day."',
      bn: 'শূন্যস্থান পূরণ করুন: "She ___ to school every day."',
      ta: 'வெற்றிடத்தை நிரப்பவும்: "She ___ to school every day."',
    },
    optionsJson: [
      { en: "go", hi: "go", mr: "go", bn: "go", ta: "go" },
      { en: "goes", hi: "goes", mr: "goes", bn: "goes", ta: "goes" },
      { en: "going", hi: "going", mr: "going", bn: "going", ta: "going" },
      { en: "gone", hi: "gone", mr: "gone", bn: "gone", ta: "gone" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The subject 'She' is third person singular, so the simple present tense verb takes an '-s': 'goes'.",
      hi: "विषय 'She' तृतीय पुरुष एकवचन है, इसलिए सामान्य वर्तमान काल की क्रिया में '-s' जुड़ता है: 'goes'।",
      mr: "'She' हा कर्ता तृतीय पुरुष एकवचनी आहे, म्हणून साध्या वर्तमानकाळाच्या क्रियापदाला '-s' जोडले जाते: 'goes'.",
      bn: "'She' কর্তা তৃতীয় পুরুষ একবচন, তাই সাধারণ বর্তমান কালের ক্রিয়ায় '-s' যুক্ত হয়: 'goes'।",
      ta: "'She' என்பது மூன்றாம் நபர் ஒருமை என்பதால், எளிய நிகழ்காலச் சொல்லுக்கு '-s' சேர்க்கப்படுகிறது: 'goes'.",
    },
  },
  {
    key: "jnvst-2021-lang-02",
    year: 2021,
    sectionKey: "language",
    difficulty: "EASY",
    questionJson: {
      en: "Choose the correct plural form of 'Mouse':",
      hi: "'Mouse' का सही बहुवचन रूप चुनें:",
      mr: "'Mouse' चे योग्य अनेकवचन रूप निवडा:",
      bn: "'Mouse'-এর সঠিক বহুবচন রূপ নির্বাচন করুন:",
      ta: "'Mouse' இன் சரியான பன்மை வடிவத்தைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Mouses", hi: "Mouses", mr: "Mouses", bn: "Mouses", ta: "Mouses" },
      { en: "Mice", hi: "Mice", mr: "Mice", bn: "Mice", ta: "Mice" },
      { en: "Mices", hi: "Mices", mr: "Mices", bn: "Mices", ta: "Mices" },
      { en: "Mouse", hi: "Mouse", mr: "Mouse", bn: "Mouse", ta: "Mouse" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "'Mouse' has an irregular plural: 'Mice', formed by changing the vowel sound, not by adding '-s'.",
      hi: "'Mouse' का अनियमित बहुवचन 'Mice' होता है, जो स्वर ध्वनि बदलकर बनता है, न कि '-s' जोड़कर।",
      mr: "'Mouse' चे अनियमित अनेकवचन 'Mice' आहे, जे स्वरध्वनी बदलून तयार होते, '-s' जोडून नाही.",
      bn: "'Mouse'-এর অনিয়মিত বহুবচন হল 'Mice', যা স্বরধ্বনি পরিবর্তন করে গঠিত হয়, '-s' যোগ করে নয়।",
      ta: "'Mouse' இன் ஒழுங்கற்ற பன்மை 'Mice' ஆகும், இது உயிரொலியை மாற்றுவதன் மூலம் உருவாகிறது, '-s' சேர்த்து அல்ல.",
    },
  },
  {
    key: "jnvst-2021-lang-03",
    year: 2021,
    sectionKey: "language",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Choose the word that is closest in meaning to 'Happy':",
      hi: "'Happy' के सबसे निकट अर्थ वाला शब्द चुनें:",
      mr: "'Happy' च्या सर्वात जवळचा अर्थ असलेला शब्द निवडा:",
      bn: "'Happy'-এর সবচেয়ে কাছাকাছি অর্থের শব্দটি নির্বাচন করুন:",
      ta: "'Happy' க்கு மிக நெருக்கமான பொருள் கொண்ட சொல்லைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Sad", hi: "Sad", mr: "Sad", bn: "Sad", ta: "Sad" },
      { en: "Joyful", hi: "Joyful", mr: "Joyful", bn: "Joyful", ta: "Joyful" },
      { en: "Angry", hi: "Angry", mr: "Angry", bn: "Angry", ta: "Angry" },
      { en: "Tired", hi: "Tired", mr: "Tired", bn: "Tired", ta: "Tired" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "'Joyful' means feeling great pleasure, the same as 'Happy'. 'Sad', 'Angry', and 'Tired' are unrelated or opposite feelings.",
      hi: "'Joyful' का अर्थ है बहुत अधिक प्रसन्नता महसूस करना, जो 'Happy' के समान है। 'Sad', 'Angry' और 'Tired' असंबंधित या विपरीत भाव हैं।",
      mr: "'Joyful' म्हणजे खूप आनंद वाटणे, जे 'Happy' सारखेच आहे. 'Sad', 'Angry' आणि 'Tired' हे असंबंधित किंवा विरुद्ध भाव आहेत.",
      bn: "'Joyful' মানে প্রবল আনন্দ অনুভব করা, যা 'Happy'-এর মতোই। 'Sad', 'Angry' এবং 'Tired' অসম্পর্কিত বা বিপরীত অনুভূতি।",
      ta: "'Joyful' என்றால் மிகுந்த மகிழ்ச்சியை உணர்வது, இது 'Happy' போன்றதே. 'Sad', 'Angry' மற்றும் 'Tired' ஆகியவை தொடர்பற்ற அல்லது எதிர் உணர்வுகள்.",
    },
  },
  {
    key: "jnvst-2021-lang-04",
    year: 2021,
    sectionKey: "language",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Choose the correctly spelled word:",
      hi: "सही वर्तनी वाला शब्द चुनें:",
      mr: "योग्य शब्दलेखन असलेला शब्द निवडा:",
      bn: "সঠিক বানানের শব্দটি নির্বাচন করুন:",
      ta: "சரியான எழுத்துப்பிழையற்ற சொல்லைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Recieve", hi: "Recieve", mr: "Recieve", bn: "Recieve", ta: "Recieve" },
      { en: "Receive", hi: "Receive", mr: "Receive", bn: "Receive", ta: "Receive" },
      { en: "Receeve", hi: "Receeve", mr: "Receeve", bn: "Receeve", ta: "Receeve" },
      { en: "Receve", hi: "Receve", mr: "Receve", bn: "Receve", ta: "Receve" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The correct spelling follows the rule 'i before e except after c': R-E-C-E-I-V-E. The other options misplace or omit letters.",
      hi: "सही वर्तनी नियम 'c के बाद को छोड़कर i, e से पहले आता है' का पालन करती है: R-E-C-E-I-V-E। अन्य विकल्पों में अक्षर गलत स्थान पर हैं या छूट गए हैं।",
      mr: "योग्य शब्दलेखन 'c नंतर वगळता i हे e च्या आधी येते' या नियमाचे पालन करते: R-E-C-E-I-V-E. इतर पर्यायांमध्ये अक्षरे चुकीच्या ठिकाणी आहेत किंवा गाळली आहेत.",
      bn: "সঠিক বানান 'c-এর পরে ছাড়া i, e-এর আগে আসে' নিয়ম মেনে চলে: R-E-C-E-I-V-E। অন্যান্য বিকল্পে অক্ষরগুলি ভুল স্থানে আছে বা বাদ পড়েছে।",
      ta: "சரியான எழுத்துப்பிழை 'c க்குப் பிறகைத் தவிர i, e க்கு முன் வரும்' என்ற விதியைப் பின்பற்றுகிறது: R-E-C-E-I-V-E. மற்ற தேர்வுகளில் எழுத்துகள் தவறான இடத்தில் உள்ளன அல்லது விடுபட்டுள்ளன.",
    },
  },
];
