import type { PyqSeedItem } from "./types";

// Original JNVST Class 6 practice questions for the "2024" cohort label.
// These are ORIGINAL questions written in the pattern/difficulty spirit
// commonly associated with JNVST — NOT verbatim reproductions of any real
// official NVS past paper. VedicNeev has no verified, licensed source for
// actual leaked/official JNVST papers; "2024" here is only a year-batch
// label for the shared question bank, not a claim of authenticity.

export const posts: PyqSeedItem[] = [
  // ── Mental Ability (8) ──────────────────────────────────────────────
  {
    key: "jnvst-2024-ma-01",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Find the missing number: 3, 6, 9, 12, ?",
      hi: "लुप्त संख्या ज्ञात करें: 3, 6, 9, 12, ?",
      mr: "गहाळ संख्या शोधा: 3, 6, 9, 12, ?",
      bn: "অনুপস্থিত সংখ্যাটি খুঁজুন: 3, 6, 9, 12, ?",
      ta: "விடுபட்ட எண்ணைக் கண்டறியவும்: 3, 6, 9, 12, ?",
    },
    optionsJson: [
      { en: "13", hi: "13", mr: "13", bn: "13", ta: "13" },
      { en: "14", hi: "14", mr: "14", bn: "14", ta: "14" },
      { en: "15", hi: "15", mr: "15", bn: "15", ta: "15" },
      { en: "18", hi: "18", mr: "18", bn: "18", ta: "18" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "Each number increases by 3: 3+3=6, 6+3=9, 9+3=12, 12+3=15. Options (a) 13 and (b) 14 break the constant gap of 3; option (d) 18 adds 6 instead of 3.",
      hi: "प्रत्येक संख्या में 3 जोड़ा जाता है: 3+3=6, 6+3=9, 9+3=12, 12+3=15। विकल्प (a) 13 और (b) 14 स्थिर अंतर 3 को तोड़ते हैं; विकल्प (d) 18 में 3 की जगह 6 जोड़ा गया है।",
      mr: "प्रत्येक संख्येत 3 मिळवले जाते: 3+3=6, 6+3=9, 9+3=12, 12+3=15. पर्याय (a) 13 आणि (b) 14 स्थिर फरक 3 मोडतात; पर्याय (d) 18 मध्ये 3 ऐवजी 6 मिळवले आहे.",
      bn: "প্রতিটি সংখ্যায় 3 যোগ করা হয়: 3+3=6, 6+3=9, 9+3=12, 12+3=15। বিকল্প (a) 13 এবং (b) 14 ধ্রুবক ব্যবধান 3 ভঙ্গ করে; বিকল্প (d) 18-এ 3-এর পরিবর্তে 6 যোগ করা হয়েছে।",
      ta: "ஒவ்வொரு எண்ணிலும் 3 கூட்டப்படுகிறது: 3+3=6, 6+3=9, 9+3=12, 12+3=15. விருப்பம் (a) 13 மற்றும் (b) 14 மாறாத இடைவெளி 3-ஐ மீறுகின்றன; விருப்பம் (d) 18-இல் 3-க்குப் பதிலாக 6 கூட்டப்பட்டுள்ளது.",
    },
  },
  {
    key: "jnvst-2024-ma-02",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Find the missing letter: B, D, F, H, ?",
      hi: "लुप्त अक्षर ज्ञात करें: B, D, F, H, ?",
      mr: "गहाळ अक्षर शोधा: B, D, F, H, ?",
      bn: "অনুপস্থিত অক্ষরটি খুঁজুন: B, D, F, H, ?",
      ta: "விடுபட்ட எழுத்தைக் கண்டறியவும்: B, D, F, H, ?",
    },
    optionsJson: [
      { en: "I", hi: "I", mr: "I", bn: "I", ta: "I" },
      { en: "J", hi: "J", mr: "J", bn: "J", ta: "J" },
      { en: "K", hi: "K", mr: "K", bn: "K", ta: "K" },
      { en: "G", hi: "G", mr: "G", bn: "G", ta: "G" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The series skips one letter each time (+2): B→D→F→H→J. Option (a) I is only +1 from H, breaking the pattern; (c) K and (d) G do not fit the +2 rule.",
      hi: "श्रृंखला हर बार एक अक्षर छोड़ती है (+2): B→D→F→H→J। विकल्प (a) I, H से केवल +1 है, जो पैटर्न को तोड़ता है; (c) K और (d) G, +2 नियम में फिट नहीं बैठते।",
      mr: "मालिका दर वेळी एक अक्षर वगळते (+2): B→D→F→H→J. पर्याय (a) I हे H पासून फक्त +1 आहे, जे पॅटर्न मोडते; (c) K आणि (d) G हे +2 नियमात बसत नाहीत.",
      bn: "ধারাটি প্রতিবার একটি অক্ষর বাদ দেয় (+2): B→D→F→H→J। বিকল্প (a) I, H থেকে মাত্র +1, যা প্যাটার্ন ভাঙে; (c) K এবং (d) G +2 নিয়মে খাপ খায় না।",
      ta: "தொடர் ஒவ்வொரு முறையும் ஒரு எழுத்தைத் தவிர்க்கிறது (+2): B→D→F→H→J. விருப்பம் (a) I என்பது H-லிருந்து +1 மட்டுமே, இது வடிவத்தை மீறுகிறது; (c) K மற்றும் (d) G ஆகியவை +2 விதிக்குப் பொருந்தவில்லை.",
    },
  },
  {
    key: "jnvst-2024-ma-03",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "EASY",
    questionJson: {
      en: "Which one does not belong with the others: Rose, Lotus, Jasmine, Mango?",
      hi: "इनमें से कौन-सा अन्य से मेल नहीं खाता: गुलाब, कमल, चमेली, आम?",
      mr: "यापैकी कोणता इतरांशी जुळत नाही: गुलाब, कमळ, चमेली, आंबा?",
      bn: "এর মধ্যে কোনটি অন্যদের সাথে মেলে না: গোলাপ, পদ্ম, বেলি, আম?",
      ta: "இவற்றில் எது மற்றவற்றுடன் பொருந்தவில்லை: ரோஜா, தாமரை, மல்லிகை, மாம்பழம்?",
    },
    optionsJson: [
      { en: "Rose", hi: "गुलाब", mr: "गुलाब", bn: "গোলাপ", ta: "ரோஜா" },
      { en: "Lotus", hi: "कमल", mr: "कमळ", bn: "পদ্ম", ta: "தாமரை" },
      { en: "Jasmine", hi: "चमेली", mr: "चमेली", bn: "বেলি", ta: "மல்லிகை" },
      { en: "Mango", hi: "आम", mr: "आंबा", bn: "আম", ta: "மாம்பழம்" },
    ],
    correctAnswer: 3,
    explanation: {
      en: "Rose, Lotus, and Jasmine are all flowers; Mango is a fruit, so it is the odd one out.",
      hi: "गुलाब, कमल और चमेली सभी फूल हैं; आम एक फल है, इसलिए यह असंगत है।",
      mr: "गुलाब, कमळ आणि चमेली हे सर्व फुले आहेत; आंबा हे फळ आहे, म्हणून तेच वेगळे आहे.",
      bn: "গোলাপ, পদ্ম এবং বেলি সবই ফুল; আম একটি ফল, তাই এটি ভিন্ন।",
      ta: "ரோஜா, தாமரை மற்றும் மல்லிகை அனைத்தும் பூக்கள்; மாம்பழம் ஒரு பழம், எனவே இதுவே பொருந்தாதது.",
    },
  },
  {
    key: "jnvst-2024-ma-04",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Doctor is to Hospital as Teacher is to ?",
      hi: "डॉक्टर का संबंध अस्पताल से है, जैसे शिक्षक का संबंध किससे है?",
      mr: "डॉक्टरचा संबंध रुग्णालयाशी आहे, तसाच शिक्षकाचा संबंध कशाशी आहे?",
      bn: "ডাক্তারের সম্পর্ক হাসপাতালের সাথে, তেমনি শিক্ষকের সম্পর্ক কীসের সাথে?",
      ta: "மருத்துவருக்கும் மருத்துவமனைக்கும் உள்ள தொடர்பு போல, ஆசிரியருக்கும் எதற்கும் தொடர்பு உள்ளது?",
    },
    optionsJson: [
      { en: "Student", hi: "छात्र", mr: "विद्यार्थी", bn: "ছাত্র", ta: "மாணவர்" },
      { en: "School", hi: "विद्यालय", mr: "शाळा", bn: "বিদ্যালয়", ta: "பள்ளி" },
      { en: "Book", hi: "किताब", mr: "पुस्तक", bn: "বই", ta: "புத்தகம்" },
      { en: "Classroom", hi: "कक्षा", mr: "वर्ग", bn: "শ্রেণিকক্ষ", ta: "வகுப்பறை" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "A Doctor works at a Hospital; similarly, a Teacher works at a School. 'Student' and 'Classroom' are related to teaching but are not the workplace itself; 'Book' is a tool, not a location.",
      hi: "एक डॉक्टर अस्पताल में काम करता है; उसी तरह, एक शिक्षक विद्यालय में काम करता है। 'छात्र' और 'कक्षा' शिक्षण से जुड़े हैं परंतु स्वयं कार्यस्थल नहीं हैं; 'किताब' एक साधन है, स्थान नहीं।",
      mr: "डॉक्टर रुग्णालयात काम करतो; त्याचप्रमाणे, शिक्षक शाळेत काम करतो. 'विद्यार्थी' आणि 'वर्ग' अध्यापनाशी संबंधित आहेत पण ते स्वतः कार्यस्थान नाहीत; 'पुस्तक' हे एक साधन आहे, स्थान नाही.",
      bn: "একজন ডাক্তার হাসপাতালে কাজ করেন; একইভাবে, একজন শিক্ষক বিদ্যালয়ে কাজ করেন। 'ছাত্র' এবং 'শ্রেণিকক্ষ' শিক্ষাদানের সাথে সম্পর্কিত কিন্তু নিজেরা কর্মস্থল নয়; 'বই' একটি উপকরণ, স্থান নয়।",
      ta: "ஒரு மருத்துவர் மருத்துவமனையில் பணிபுரிகிறார்; அதேபோல, ஒரு ஆசிரியர் பள்ளியில் பணிபுரிகிறார். 'மாணவர்' மற்றும் 'வகுப்பறை' கற்பித்தலுடன் தொடர்புடையவை ஆனால் அவையே பணியிடம் அல்ல; 'புத்தகம்' ஒரு கருவி, இடம் அல்ல.",
    },
  },
  {
    key: "jnvst-2024-ma-05",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "In a certain code, CAT is written as DBU. How is DOG written in that code?",
      hi: "एक निश्चित कोड में, CAT को DBU लिखा जाता है। उसी कोड में DOG कैसे लिखा जाएगा?",
      mr: "एका ठराविक कोडमध्ये, CAT हे DBU असे लिहिले जाते. त्याच कोडमध्ये DOG कसे लिहिले जाईल?",
      bn: "একটি নির্দিষ্ট কোডে, CAT-কে DBU লেখা হয়। সেই একই কোডে DOG কীভাবে লেখা হবে?",
      ta: "ஒரு குறிப்பிட்ட குறியீட்டில், CAT என்பது DBU என எழுதப்படுகிறது. அதே குறியீட்டில் DOG எவ்வாறு எழுதப்படும்?",
    },
    optionsJson: [
      { en: "EPH", hi: "EPH", mr: "EPH", bn: "EPH", ta: "EPH" },
      { en: "DPH", hi: "DPH", mr: "DPH", bn: "DPH", ta: "DPH" },
      { en: "EPG", hi: "EPG", mr: "EPG", bn: "EPG", ta: "EPG" },
      { en: "FQI", hi: "FQI", mr: "FQI", bn: "FQI", ta: "FQI" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Each letter of the word is shifted forward by one place in the alphabet: C→D, A→B, T→U. Applying the same rule to DOG: D→E, O→P, G→H, giving EPH. Option (b) leaves D unshifted, (c) leaves G unshifted, and (d) shifts by two places instead of one.",
      hi: "शब्द के प्रत्येक अक्षर को वर्णमाला में एक स्थान आगे खिसकाया जाता है: C→D, A→B, T→U। यही नियम DOG पर लागू करने पर: D→E, O→P, G→H, जिससे EPH प्राप्त होता है। विकल्प (b) में D को नहीं खिसकाया गया, (c) में G को नहीं खिसकाया गया, और (d) में एक की बजाय दो स्थान खिसकाया गया है।",
      mr: "शब्दातील प्रत्येक अक्षर वर्णमालेत एक स्थान पुढे सरकवले जाते: C→D, A→B, T→U. हाच नियम DOG ला लावल्यास: D→E, O→P, G→H, म्हणजे EPH मिळते. पर्याय (b) मध्ये D सरकवलेले नाही, (c) मध्ये G सरकवलेले नाही, आणि (d) मध्ये एकाऐवजी दोन स्थाने सरकवली आहेत.",
      bn: "শব্দের প্রতিটি অক্ষরকে বর্ণমালায় একটি স্থান এগিয়ে সরানো হয়: C→D, A→B, T→U। একই নিয়ম DOG-তে প্রয়োগ করলে: D→E, O→P, G→H, ফলে EPH পাওয়া যায়। বিকল্প (b)-তে D সরানো হয়নি, (c)-তে G সরানো হয়নি, এবং (d)-তে একটির পরিবর্তে দুটি স্থান সরানো হয়েছে।",
      ta: "சொல்லின் ஒவ்வொரு எழுத்தும் அகரவரிசையில் ஒரு இடம் முன்னோக்கி நகர்த்தப்படுகிறது: C→D, A→B, T→U. அதே விதியை DOG-க்குப் பயன்படுத்தினால்: D→E, O→P, G→H, இதனால் EPH கிடைக்கிறது. விருப்பம் (b)-இல் D நகர்த்தப்படவில்லை, (c)-இல் G நகர்த்தப்படவில்லை, (d)-இல் ஒன்றுக்குப் பதிலாக இரண்டு இடங்கள் நகர்த்தப்பட்டுள்ளன.",
    },
  },
  {
    key: "jnvst-2024-ma-06",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Find the missing number in the pattern: 2, 5, 10, 17, 26, ?",
      hi: "पैटर्न में लुप्त संख्या ज्ञात करें: 2, 5, 10, 17, 26, ?",
      mr: "पॅटर्नमधील गहाळ संख्या शोधा: 2, 5, 10, 17, 26, ?",
      bn: "প্যাটার্নে অনুপস্থিত সংখ্যাটি খুঁজুন: 2, 5, 10, 17, 26, ?",
      ta: "வடிவத்தில் விடுபட்ட எண்ணைக் கண்டறியவும்: 2, 5, 10, 17, 26, ?",
    },
    optionsJson: [
      { en: "35", hi: "35", mr: "35", bn: "35", ta: "35" },
      { en: "36", hi: "36", mr: "36", bn: "36", ta: "36" },
      { en: "37", hi: "37", mr: "37", bn: "37", ta: "37" },
      { en: "39", hi: "39", mr: "39", bn: "39", ta: "39" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "Each term equals n²+1 for its position: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, so the 6th term is 6²+1=37.",
      hi: "प्रत्येक पद अपनी स्थिति n के लिए n²+1 के बराबर है: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, इसलिए छठा पद 6²+1=37 है।",
      mr: "प्रत्येक पद त्याच्या स्थान n साठी n²+1 इतके आहे: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, म्हणून सहावे पद 6²+1=37 आहे.",
      bn: "প্রতিটি পদ তার অবস্থান n-এর জন্য n²+1 এর সমান: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, তাই ষষ্ঠ পদটি 6²+1=37।",
      ta: "ஒவ்வொரு உறுப்பும் அதன் இடம் n-க்கு n²+1 என்பதற்கு சமம்: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, எனவே ஆறாவது உறுப்பு 6²+1=37.",
    },
  },
  {
    key: "jnvst-2024-ma-07",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "HARD",
    questionJson: {
      en: "Find the missing number: 4, 9, 19, 39, ?",
      hi: "लुप्त संख्या ज्ञात करें: 4, 9, 19, 39, ?",
      mr: "गहाळ संख्या शोधा: 4, 9, 19, 39, ?",
      bn: "অনুপস্থিত সংখ্যাটি খুঁজুন: 4, 9, 19, 39, ?",
      ta: "விடுபட்ட எண்ணைக் கண்டறியவும்: 4, 9, 19, 39, ?",
    },
    optionsJson: [
      { en: "69", hi: "69", mr: "69", bn: "69", ta: "69" },
      { en: "74", hi: "74", mr: "74", bn: "74", ta: "74" },
      { en: "78", hi: "78", mr: "78", bn: "78", ta: "78" },
      { en: "79", hi: "79", mr: "79", bn: "79", ta: "79" },
    ],
    correctAnswer: 3,
    explanation: {
      en: "Each term is double the previous term plus 1: 4×2+1=9, 9×2+1=19, 19×2+1=39, 39×2+1=79. Option (c) 78 comes from doubling without adding 1 — a common slip; options (a) 69 and (b) 74 are arithmetic near-misses that don't satisfy the rule.",
      hi: "प्रत्येक पद पिछले पद का दोगुना करके फिर 1 जोड़ने से प्राप्त होता है: 4×2+1=9, 9×2+1=19, 19×2+1=39, 39×2+1=79। विकल्प (c) 78, 1 जोड़े बिना केवल दोगुना करने से आता है — यह एक सामान्य भूल है; (a) 69 और (b) 74 अंकगणितीय त्रुटियों से बने हैं और नियम को संतुष्ट नहीं करते।",
      mr: "प्रत्येक पद मागील पदाच्या दुप्पट करून नंतर 1 मिळवून तयार होते: 4×2+1=9, 9×2+1=19, 19×2+1=39, 39×2+1=79. पर्याय (c) 78 हे 1 न मिळवता फक्त दुप्पट केल्याने येते — ही एक सामान्य चूक आहे; (a) 69 आणि (b) 74 अंकगणितीय चुकांमुळे तयार झाले आहेत आणि नियम पूर्ण करत नाहीत.",
      bn: "প্রতিটি পদ আগের পদকে দ্বিগুণ করে তারপর 1 যোগ করে পাওয়া যায়: 4×2+1=9, 9×2+1=19, 19×2+1=39, 39×2+1=79। বিকল্প (c) 78 আসে 1 যোগ না করে শুধু দ্বিগুণ করা থেকে — এটি একটি সাধারণ ভুল; (a) 69 এবং (b) 74 গাণিতিক ত্রুটি থেকে তৈরি এবং নিয়ম পূরণ করে না।",
      ta: "ஒவ்வொரு உறுப்பும் முந்தைய உறுப்பை இரட்டிப்பாக்கி பின்னர் 1 கூட்டுவதன் மூலம் கிடைக்கிறது: 4×2+1=9, 9×2+1=19, 19×2+1=39, 39×2+1=79. விருப்பம் (c) 78 என்பது 1 கூட்டாமல் வெறும் இரட்டிப்பாக்குவதால் வருகிறது — இது ஒரு பொதுவான தவறு; (a) 69 மற்றும் (b) 74 ஆகியவை கணக்கீட்டுப் பிழைகளால் உருவானவை, விதிக்குப் பொருந்தவில்லை.",
    },
  },
  {
    key: "jnvst-2024-ma-08",
    year: 2024,
    sectionKey: "mental_ability",
    difficulty: "HARD",
    questionJson: {
      en: "In a certain code, SUN IS HOT is written as TVO JT IPU. How will ICE IS COLD be written in that code?",
      hi: "एक निश्चित कोड में, SUN IS HOT को TVO JT IPU लिखा जाता है। उसी कोड में ICE IS COLD कैसे लिखा जाएगा?",
      mr: "एका ठराविक कोडमध्ये, SUN IS HOT हे TVO JT IPU असे लिहिले जाते. त्याच कोडमध्ये ICE IS COLD कसे लिहिले जाईल?",
      bn: "একটি নির্দিষ্ট কোডে, SUN IS HOT-কে TVO JT IPU লেখা হয়। সেই একই কোডে ICE IS COLD কীভাবে লেখা হবে?",
      ta: "ஒரு குறிப்பிட்ட குறியீட்டில், SUN IS HOT என்பது TVO JT IPU என எழுதப்படுகிறது. அதே குறியீட்டில் ICE IS COLD எவ்வாறு எழுதப்படும்?",
    },
    optionsJson: [
      { en: "JDF JT DPME", hi: "JDF JT DPME", mr: "JDF JT DPME", bn: "JDF JT DPME", ta: "JDF JT DPME" },
      { en: "IDF JT DPME", hi: "IDF JT DPME", mr: "IDF JT DPME", bn: "IDF JT DPME", ta: "IDF JT DPME" },
      { en: "JDF IT DPME", hi: "JDF IT DPME", mr: "JDF IT DPME", bn: "JDF IT DPME", ta: "JDF IT DPME" },
      { en: "JCE JT DPME", hi: "JCE JT DPME", mr: "JCE JT DPME", bn: "JCE JT DPME", ta: "JCE JT DPME" },
    ],
    correctAnswer: 0,
    explanation: {
      en: "Every letter in the code shifts one place forward in the alphabet (S→T, U→V, N→O; I→J, S→T; H→I, O→P, T→U). Applying the same +1 shift to ICE IS COLD: I→J, C→D, E→F gives JDF; I→J, S→T gives JT; C→D, O→P, L→M, D→E gives DPME. So the full code is JDF JT DPME. Options (b)-(d) each leave one letter un-shifted by mistake.",
      hi: "कोड में प्रत्येक अक्षर वर्णमाला में एक स्थान आगे खिसकता है (S→T, U→V, N→O; I→J, S→T; H→I, O→P, T→U)। यही +1 नियम ICE IS COLD पर लागू करने पर: I→J, C→D, E→F से JDF; I→J, S→T से JT; C→D, O→P, L→M, D→E से DPME प्राप्त होता है। इस प्रकार पूरा कोड JDF JT DPME है। विकल्प (b)-(d) में से प्रत्येक में गलती से एक अक्षर बिना खिसकाए छोड़ दिया गया है।",
      mr: "कोडमध्ये प्रत्येक अक्षर वर्णमालेत एक स्थान पुढे सरकते (S→T, U→V, N→O; I→J, S→T; H→I, O→P, T→U). हाच +1 नियम ICE IS COLD ला लावल्यास: I→J, C→D, E→F मुळे JDF; I→J, S→T मुळे JT; C→D, O→P, L→M, D→E मुळे DPME मिळते. अशा प्रकारे संपूर्ण कोड JDF JT DPME आहे. पर्याय (b)-(d) यांपैकी प्रत्येकात चुकून एक अक्षर न सरकवता तसेच ठेवले आहे.",
      bn: "কোডে প্রতিটি অক্ষর বর্ণমালায় একটি স্থান এগিয়ে সরে (S→T, U→V, N→O; I→J, S→T; H→I, O→P, T→U)। একই +1 নিয়ম ICE IS COLD-তে প্রয়োগ করলে: I→J, C→D, E→F থেকে JDF; I→J, S→T থেকে JT; C→D, O→P, L→M, D→E থেকে DPME পাওয়া যায়। এভাবে সম্পূর্ণ কোডটি হল JDF JT DPME। বিকল্প (b)-(d) প্রতিটিতে ভুলবশত একটি অক্ষর না সরিয়ে রাখা হয়েছে।",
      ta: "குறியீட்டில் ஒவ்வொரு எழுத்தும் அகரவரிசையில் ஒரு இடம் முன்னோக்கி நகர்கிறது (S→T, U→V, N→O; I→J, S→T; H→I, O→P, T→U). அதே +1 விதியை ICE IS COLD-க்குப் பயன்படுத்தினால்: I→J, C→D, E→F என்பதால் JDF; I→J, S→T என்பதால் JT; C→D, O→P, L→M, D→E என்பதால் DPME கிடைக்கிறது. இவ்வாறு முழு குறியீடும் JDF JT DPME ஆகும். விருப்பங்கள் (b)-(d) ஒவ்வொன்றிலும் தவறுதலாக ஒரு எழுத்து நகர்த்தப்படாமல் விடப்பட்டுள்ளது.",
    },
  },

  // ── Arithmetic (4) — Nikhilam sutra + multiply-by-11 sandwich rule ──
  {
    key: "jnvst-2024-ar-01",
    year: 2024,
    sectionKey: "arithmetic",
    difficulty: "EASY",
    questionJson: {
      en: "Calculate quickly using the ×11 sandwich rule: 63 × 11 = ?",
      hi: "×11 सैंडविच नियम का उपयोग करके शीघ्र गणना करें: 63 × 11 = ?",
      mr: "×11 सँडविच नियम वापरून शीघ्र गणना करा: 63 × 11 = ?",
      bn: "×11 স্যান্ডউইচ নিয়ম ব্যবহার করে দ্রুত হিসাব করুন: 63 × 11 = ?",
      ta: "×11 சாண்ட்விச் விதியைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 63 × 11 = ?",
    },
    optionsJson: [
      { en: "683", hi: "683", mr: "683", bn: "683", ta: "683" },
      { en: "693", hi: "693", mr: "693", bn: "693", ta: "693" },
      { en: "663", hi: "663", mr: "663", bn: "663", ta: "663" },
      { en: "723", hi: "723", mr: "723", bn: "723", ta: "723" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "Sandwich rule for ×11: place the sum of the digits between them. For 63: outer digits are 6 and 3, and the middle digit is their sum, 6+3=9, giving 693. Options (a) and (c) use the wrong middle digit, and (d) is not close to the pattern at all.",
      hi: "×11 के लिए सैंडविच नियम: अंकों के योग को उनके बीच रखें। 63 के लिए: बाहरी अंक 6 और 3 हैं, और मध्य अंक उनका योग है, 6+3=9, जिससे 693 प्राप्त होता है। विकल्प (a) और (c) गलत मध्य अंक का उपयोग करते हैं, और (d) पैटर्न के करीब भी नहीं है।",
      mr: "×11 साठी सँडविच नियम: अंकांची बेरीज त्यांच्यामध्ये ठेवा. 63 साठी: बाहेरील अंक 6 आणि 3 आहेत, आणि मधला अंक त्यांची बेरीज आहे, 6+3=9, ज्यामुळे 693 मिळते. पर्याय (a) आणि (c) चुकीचा मधला अंक वापरतात, आणि (d) पॅटर्नच्या जवळपासही नाही.",
      bn: "×11-এর জন্য স্যান্ডউইচ নিয়ম: অঙ্কগুলির যোগফল তাদের মাঝে বসান। 63-এর জন্য: বাইরের অঙ্ক 6 এবং 3, এবং মাঝের অঙ্কটি তাদের যোগফল, 6+3=9, যা 693 দেয়। বিকল্প (a) এবং (c) ভুল মাঝের অঙ্ক ব্যবহার করে, এবং (d) প্যাটার্নের কাছাকাছিও নয়।",
      ta: "×11க்கான சாண்ட்விச் விதி: இலக்கங்களின் கூட்டுத்தொகையை அவற்றுக்கு இடையே வைக்கவும். 63-க்கு: வெளிப்புற இலக்கங்கள் 6 மற்றும் 3, நடு இலக்கம் அவற்றின் கூட்டுத்தொகை, 6+3=9, இது 693-ஐ தருகிறது. விருப்பங்கள் (a) மற்றும் (c) தவறான நடு இலக்கத்தைப் பயன்படுத்துகின்றன, (d) வடிவத்திற்கு நெருக்கமாகக் கூட இல்லை.",
    },
  },
  {
    key: "jnvst-2024-ar-02",
    year: 2024,
    sectionKey: "arithmetic",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Use the Nikhilam (base) method to calculate quickly: 102 × 104 = ?",
      hi: "निखिलम् (आधार) विधि का उपयोग करके शीघ्र गणना करें: 102 × 104 = ?",
      mr: "निखिलम् (आधार) पद्धत वापरून शीघ्र गणना करा: 102 × 104 = ?",
      bn: "নিখিলম্ (ভিত্তি) পদ্ধতি ব্যবহার করে দ্রুত হিসাব করুন: 102 × 104 = ?",
      ta: "நிகிலம் (அடிப்படை) முறையைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 102 × 104 = ?",
    },
    optionsJson: [
      { en: "10408", hi: "10408", mr: "10408", bn: "10408", ta: "10408" },
      { en: "10508", hi: "10508", mr: "10508", bn: "10508", ta: "10508" },
      { en: "10608", hi: "10608", mr: "10608", bn: "10608", ta: "10608" },
      { en: "10708", hi: "10708", mr: "10708", bn: "10708", ta: "10708" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "Base 100, deviations +2 and +4: cross-add one number and the other's deviation, (102+4)=106, multiply by the base 100 → 10600, then add the product of the deviations, 2×4=8, giving 10600+8=10608. Options (a), (b), and (d) come from adding the wrong deviation product.",
      hi: "आधार 100, विचलन +2 और +4: एक संख्या में दूसरी के विचलन को जोड़ें, (102+4)=106, आधार 100 से गुणा करें → 10600, फिर विचलनों का गुणनफल जोड़ें, 2×4=8, जिससे 10600+8=10608 प्राप्त होता है। विकल्प (a), (b) और (d) गलत विचलन गुणनफल जोड़ने से बनते हैं।",
      mr: "आधार 100, विचलन +2 आणि +4: एका संख्येत दुसऱ्याचे विचलन मिळवा, (102+4)=106, आधार 100 ने गुणा करा → 10600, नंतर विचलनांचा गुणाकार मिळवा, 2×4=8, ज्यामुळे 10600+8=10608 मिळते. पर्याय (a), (b) आणि (d) चुकीचा विचलन गुणाकार मिळवल्याने तयार होतात.",
      bn: "ভিত্তি 100, বিচ্যুতি +2 এবং +4: একটি সংখ্যায় অন্যটির বিচ্যুতি যোগ করুন, (102+4)=106, ভিত্তি 100 দিয়ে গুণ করুন → 10600, তারপর বিচ্যুতিগুলির গুণফল যোগ করুন, 2×4=8, যাতে 10600+8=10608 পাওয়া যায়। বিকল্প (a), (b) এবং (d) ভুল বিচ্যুতি গুণফল যোগ করা থেকে তৈরি।",
      ta: "அடிப்படை 100, விலகல்கள் +2 மற்றும் +4: ஒரு எண்ணுடன் மற்றொன்றின் விலகலைக் கூட்டவும், (102+4)=106, அடிப்படை 100 ஆல் பெருக்கவும் → 10600, பின்னர் விலகல்களின் பெருக்குத்தொகையைக் கூட்டவும், 2×4=8, இது 10600+8=10608-ஐ தருகிறது. விருப்பங்கள் (a), (b) மற்றும் (d) தவறான விலகல் பெருக்குத்தொகையைக் கூட்டுவதால் உருவாகின்றன.",
    },
  },
  {
    key: "jnvst-2024-ar-03",
    year: 2024,
    sectionKey: "arithmetic",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Use the Nikhilam (base) method to calculate quickly: 94 × 98 = ?",
      hi: "निखिलम् (आधार) विधि का उपयोग करके शीघ्र गणना करें: 94 × 98 = ?",
      mr: "निखिलम् (आधार) पद्धत वापरून शीघ्र गणना करा: 94 × 98 = ?",
      bn: "নিখিলম্ (ভিত্তি) পদ্ধতি ব্যবহার করে দ্রুত হিসাব করুন: 94 × 98 = ?",
      ta: "நிகிலம் (அடிப்படை) முறையைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 94 × 98 = ?",
    },
    optionsJson: [
      { en: "9112", hi: "9112", mr: "9112", bn: "9112", ta: "9112" },
      { en: "9212", hi: "9212", mr: "9212", bn: "9212", ta: "9212" },
      { en: "9312", hi: "9312", mr: "9312", bn: "9312", ta: "9312" },
      { en: "9202", hi: "9202", mr: "9202", bn: "9202", ta: "9202" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "Base 100, deviations -6 and -2: cross-subtract, (94-2)=92, multiply by the base 100 → 9200, then add the product of the deviations (both negative, so their product is positive), (-6)×(-2)=12, giving 9200+12=9212. Options (a) and (c) use a slightly wrong cross-difference, and (d) adds only 2 instead of 12.",
      hi: "आधार 100, विचलन -6 और -2: तिरछा घटाव करें, (94-2)=92, आधार 100 से गुणा करें → 9200, फिर विचलनों का गुणनफल जोड़ें (दोनों ऋणात्मक हैं, इसलिए गुणनफल धनात्मक है), (-6)×(-2)=12, जिससे 9200+12=9212 प्राप्त होता है। विकल्प (a) और (c) थोड़े गलत तिरछे अंतर का उपयोग करते हैं, और (d) में केवल 2 जोड़ा गया है, 12 नहीं।",
      mr: "आधार 100, विचलन -6 आणि -2: तिरकस वजाबाकी करा, (94-2)=92, आधार 100 ने गुणा करा → 9200, नंतर विचलनांचा गुणाकार मिळवा (दोन्ही ऋण असल्याने गुणाकार धन आहे), (-6)×(-2)=12, ज्यामुळे 9200+12=9212 मिळते. पर्याय (a) आणि (c) थोडा चुकीचा तिरकस फरक वापरतात, आणि (d) मध्ये फक्त 2 मिळवले आहे, 12 नाही.",
      bn: "ভিত্তি 100, বিচ্যুতি -6 এবং -2: তির্যক বিয়োগ করুন, (94-2)=92, ভিত্তি 100 দিয়ে গুণ করুন → 9200, তারপর বিচ্যুতিগুলির গুণফল যোগ করুন (উভয়ই ঋণাত্মক, তাই গুণফল ধনাত্মক), (-6)×(-2)=12, যাতে 9200+12=9212 পাওয়া যায়। বিকল্প (a) এবং (c) সামান্য ভুল তির্যক পার্থক্য ব্যবহার করে, এবং (d)-তে শুধু 2 যোগ করা হয়েছে, 12 নয়।",
      ta: "அடிப்படை 100, விலகல்கள் -6 மற்றும் -2: குறுக்கு கழித்தல் செய்யவும், (94-2)=92, அடிப்படை 100 ஆல் பெருக்கவும் → 9200, பின்னர் விலகல்களின் பெருக்குத்தொகையைக் கூட்டவும் (இரண்டும் எதிர்மறை என்பதால் பெருக்குத்தொகை நேர்மறை), (-6)×(-2)=12, இது 9200+12=9212-ஐ தருகிறது. விருப்பங்கள் (a) மற்றும் (c) சற்று தவறான குறுக்கு வித்தியாசத்தைப் பயன்படுத்துகின்றன, (d)-இல் 12-க்குப் பதிலாக 2 மட்டுமே கூட்டப்பட்டுள்ளது.",
    },
  },
  {
    key: "jnvst-2024-ar-04",
    year: 2024,
    sectionKey: "arithmetic",
    difficulty: "HARD",
    questionJson: {
      en: "Calculate quickly using the ×11 sandwich rule: 158 × 11 = ?",
      hi: "×11 सैंडविच नियम का उपयोग करके शीघ्र गणना करें: 158 × 11 = ?",
      mr: "×11 सँडविच नियम वापरून शीघ्र गणना करा: 158 × 11 = ?",
      bn: "×11 স্যান্ডউইচ নিয়ম ব্যবহার করে দ্রুত হিসাব করুন: 158 × 11 = ?",
      ta: "×11 சாண்ட்விச் விதியைப் பயன்படுத்தி விரைவாகக் கணக்கிடுங்கள்: 158 × 11 = ?",
    },
    optionsJson: [
      { en: "1638", hi: "1638", mr: "1638", bn: "1638", ta: "1638" },
      { en: "1728", hi: "1728", mr: "1728", bn: "1728", ta: "1728" },
      { en: "1738", hi: "1738", mr: "1738", bn: "1738", ta: "1738" },
      { en: "1748", hi: "1748", mr: "1748", bn: "1748", ta: "1748" },
    ],
    correctAnswer: 2,
    explanation: {
      en: "For a 3-digit number, sandwich rule: write the first digit, then the sum of each adjacent pair, then the last digit, carrying over when a sum exceeds 9. For 158: first digit 1; 1+5=6; 5+8=13 (write 3, carry 1); last digit 8. Adding the carry to the previous digit: 6+1=7. Reading left to right: 1, 7, 3, 8 → 1738. Options (a), (b), and (d) forget to carry the 1 from 5+8=13 into the next digit.",
      hi: "तीन अंकों की संख्या के लिए, सैंडविच नियम: पहला अंक लिखें, फिर प्रत्येक आसन्न जोड़े का योग, फिर अंतिम अंक, और जब योग 9 से अधिक हो तो कैरी करें। 158 के लिए: पहला अंक 1; 1+5=6; 5+8=13 (3 लिखें, 1 कैरी करें); अंतिम अंक 8। कैरी को पिछले अंक में जोड़ें: 6+1=7। बाएं से दाएं पढ़ने पर: 1, 7, 3, 8 → 1738। विकल्प (a), (b) और (d) में 5+8=13 से आने वाले 1 के कैरी को अगले अंक में जोड़ना भूल गए हैं।",
      mr: "तीन अंकी संख्येसाठी, सँडविच नियम: पहिला अंक लिहा, नंतर प्रत्येक लगतच्या जोडीची बेरीज, नंतर शेवटचा अंक, आणि बेरीज 9 पेक्षा जास्त झाल्यास कॅरी करा. 158 साठी: पहिला अंक 1; 1+5=6; 5+8=13 (3 लिहा, 1 कॅरी करा); शेवटचा अंक 8. कॅरी मागील अंकात मिळवा: 6+1=7. डावीकडून उजवीकडे वाचल्यास: 1, 7, 3, 8 → 1738. पर्याय (a), (b) आणि (d) मध्ये 5+8=13 मधून येणारा 1 चा कॅरी पुढील अंकात मिळवायला विसरले आहेत.",
      bn: "তিন অঙ্কের সংখ্যার জন্য, স্যান্ডউইচ নিয়ম: প্রথম অঙ্কটি লিখুন, তারপর প্রতিটি পাশাপাশি জোড়ার যোগফল, তারপর শেষ অঙ্কটি, এবং যোগফল 9-এর বেশি হলে ক্যারি করুন। 158-এর জন্য: প্রথম অঙ্ক 1; 1+5=6; 5+8=13 (3 লিখুন, 1 ক্যারি করুন); শেষ অঙ্ক 8। ক্যারিটি আগের অঙ্কে যোগ করুন: 6+1=7। বাম থেকে ডানে পড়লে: 1, 7, 3, 8 → 1738। বিকল্প (a), (b) এবং (d)-তে 5+8=13 থেকে আসা 1-এর ক্যারি পরবর্তী অঙ্কে যোগ করতে ভুলে গেছে।",
      ta: "மூன்று இலக்க எண்ணுக்கு, சாண்ட்விச் விதி: முதல் இலக்கத்தை எழுதவும், பின்னர் ஒவ்வொரு அருகிலுள்ள ஜோடியின் கூட்டுத்தொகை, பின்னர் கடைசி இலக்கம், கூட்டுத்தொகை 9-ஐ விட அதிகமாக இருந்தால் தூக்கிச் செல்லவும். 158-க்கு: முதல் இலக்கம் 1; 1+5=6; 5+8=13 (3 எழுதவும், 1 தூக்கிச் செல்லவும்); கடைசி இலக்கம் 8. தூக்கிச் செல்லப்பட்டதை முந்தைய இலக்கத்துடன் கூட்டவும்: 6+1=7. இடமிருந்து வலமாகப் படித்தால்: 1, 7, 3, 8 → 1738. விருப்பங்கள் (a), (b) மற்றும் (d) ஆகியவற்றில் 5+8=13-இலிருந்து வரும் 1-ஐ அடுத்த இலக்கத்துடன் கூட்ட மறந்துவிட்டனர்.",
    },
  },

  // ── Language (4) ─────────────────────────────────────────────────────
  {
    key: "jnvst-2024-lang-01",
    year: 2024,
    sectionKey: "language",
    difficulty: "EASY",
    questionJson: {
      en: "Choose the correct plural form of 'Mouse':",
      hi: "'Mouse' का सही बहुवचन रूप चुनें:",
      mr: "'Mouse' चे योग्य अनेकवचन रूप निवडा:",
      bn: "'Mouse'-এর সঠিক বহুবচন রূপ নির্বাচন করুন:",
      ta: "'Mouse' இன் சரியான பன்மை வடிவத்தைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Mouses", hi: "Mouses", mr: "Mouses", bn: "Mouses", ta: "Mouses" },
      { en: "Mice", hi: "Mice", mr: "Mice", bn: "Mice", ta: "Mice" },
      { en: "Mouse", hi: "Mouse", mr: "Mouse", bn: "Mouse", ta: "Mouse" },
      { en: "Mices", hi: "Mices", mr: "Mices", bn: "Mices", ta: "Mices" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "'Mouse' has an irregular plural: 'Mice', not formed by adding '-s' or '-es'.",
      hi: "'Mouse' का अनियमित बहुवचन 'Mice' होता है, न कि '-s' या '-es' जोड़कर।",
      mr: "'Mouse' चे अनियमित अनेकवचन 'Mice' आहे, '-s' किंवा '-es' जोडून नाही.",
      bn: "'Mouse'-এর অনিয়মিত বহুবচন হল 'Mice', '-s' বা '-es' যোগ করে নয়।",
      ta: "'Mouse' இன் ஒழுங்கற்ற பன்மை 'Mice' ஆகும், '-s' அல்லது '-es' சேர்த்து அல்ல.",
    },
  },
  {
    key: "jnvst-2024-lang-02",
    year: 2024,
    sectionKey: "language",
    difficulty: "EASY",
    questionJson: {
      en: "Choose the correctly spelled word:",
      hi: "सही वर्तनी वाला शब्द चुनें:",
      mr: "योग्य शब्दलेखन असलेला शब्द निवडा:",
      bn: "সঠিক বানানের শব্দটি নির্বাচন করুন:",
      ta: "சரியான எழுத்துப்பிழையற்ற வார்த்தையைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Recieve", hi: "Recieve", mr: "Recieve", bn: "Recieve", ta: "Recieve" },
      { en: "Receive", hi: "Receive", mr: "Receive", bn: "Receive", ta: "Receive" },
      { en: "Receeve", hi: "Receeve", mr: "Receeve", bn: "Receeve", ta: "Receeve" },
      { en: "Receve", hi: "Receve", mr: "Receve", bn: "Receve", ta: "Receve" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The correct spelling is 'Receive'. English follows the rule 'i before e, except after c' — since the word has a 'c' right before this vowel pair, the order flips to 'ei', giving 'Receive', not 'Recieve'.",
      hi: "सही वर्तनी 'Receive' है। अंग्रेजी में नियम है 'i before e, except after c' — चूंकि इस शब्द में स्वर-युग्म से ठीक पहले 'c' आता है, इसलिए क्रम बदलकर 'ei' हो जाता है, जिससे 'Receive' बनता है, न कि 'Recieve'।",
      mr: "योग्य शब्दलेखन 'Receive' आहे. इंग्रजीत नियम आहे 'i before e, except after c' — कारण या शब्दात स्वर-जोडीच्या आधी 'c' येते, म्हणून क्रम बदलून 'ei' होतो, ज्यामुळे 'Receive' तयार होते, 'Recieve' नाही.",
      bn: "সঠিক বানান হল 'Receive'। ইংরেজিতে নিয়ম আছে 'i before e, except after c' — যেহেতু এই শব্দে স্বরযুগলের ঠিক আগে 'c' আছে, তাই ক্রম পাল্টে 'ei' হয়, যাতে 'Receive' তৈরি হয়, 'Recieve' নয়।",
      ta: "சரியான எழுத்துப்பிழை 'Receive' ஆகும். ஆங்கிலத்தில் 'i before e, except after c' என்ற விதி உள்ளது — இந்த வார்த்தையில் உயிரெழுத்து ஜோடிக்கு முன் 'c' வருவதால், வரிசை மாறி 'ei' ஆகிறது, இதனால் 'Recieve' அல்ல, 'Receive' உருவாகிறது.",
    },
  },
  {
    key: "jnvst-2024-lang-03",
    year: 2024,
    sectionKey: "language",
    difficulty: "MEDIUM",
    questionJson: {
      en: 'Fill in the blank: "She ___ to school every day."',
      hi: 'रिक्त स्थान भरें: "She ___ to school every day."',
      mr: 'रिकामी जागा भरा: "She ___ to school every day."',
      bn: 'শূন্যস্থান পূরণ করুন: "She ___ to school every day."',
      ta: 'வெற்றிடத்தை நிரப்பவும்: "She ___ to school every day."',
    },
    optionsJson: [
      { en: "go", hi: "go", mr: "go", bn: "go", ta: "go" },
      { en: "goes", hi: "goes", mr: "goes", bn: "goes", ta: "goes" },
      { en: "going", hi: "going", mr: "going", bn: "going", ta: "going" },
      { en: "gone", hi: "gone", mr: "gone", bn: "gone", ta: "gone" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "The subject 'She' is third-person singular, and the sentence describes a habitual action in the present tense, so the verb takes an '-s': 'goes'. 'Go' is for I/you/we/they; 'going' needs a helping verb like 'is'; 'gone' is a past participle.",
      hi: "कर्ता 'She' तृतीय पुरुष एकवचन है, और वाक्य वर्तमान काल में एक नियमित क्रिया का वर्णन करता है, इसलिए क्रिया में '-s' जुड़ता है: 'goes'। 'Go' का प्रयोग I/you/we/they के साथ होता है; 'going' के लिए 'is' जैसी सहायक क्रिया चाहिए; 'gone' भूतकालिक कृदंत (past participle) है।",
      mr: "कर्ता 'She' तृतीय पुरुष एकवचनी आहे, आणि वाक्य वर्तमानकाळात एक नियमित क्रिया दर्शवते, म्हणून क्रियापदाला '-s' जोडले जाते: 'goes'. 'Go' चा वापर I/you/we/they बरोबर होतो; 'going' साठी 'is' सारखे साहाय्यक क्रियापद लागते; 'gone' हे भूतकालवाचक कृदंत (past participle) आहे.",
      bn: "কর্তা 'She' তৃতীয় পুরুষ একবচন, এবং বাক্যটি বর্তমান কালে একটি অভ্যাসগত ক্রিয়া বর্ণনা করে, তাই ক্রিয়াপদে '-s' যুক্ত হয়: 'goes'। 'Go' ব্যবহৃত হয় I/you/we/they-এর সাথে; 'going'-এর জন্য 'is'-এর মতো সহায়ক ক্রিয়া দরকার; 'gone' একটি অতীত কৃদন্ত (past participle)।",
      ta: "எழுவாய் 'She' மூன்றாம் நபர் ஒருமை, மேலும் இந்த வாக்கியம் நிகழ்காலத்தில் ஒரு வழக்கமான செயலை விவரிக்கிறது, எனவே வினைச்சொல்லுடன் '-s' சேர்க்கப்படுகிறது: 'goes'. 'Go' என்பது I/you/we/they உடன் பயன்படுத்தப்படும்; 'going'-க்கு 'is' போன்ற துணை வினை தேவை; 'gone' என்பது இறந்தகால பகுதி (past participle).",
    },
  },
  {
    key: "jnvst-2024-lang-04",
    year: 2024,
    sectionKey: "language",
    difficulty: "MEDIUM",
    questionJson: {
      en: "Choose the antonym of 'Brave':",
      hi: "'Brave' का विलोम शब्द चुनें:",
      mr: "'Brave' चा विरुद्धार्थी शब्द निवडा:",
      bn: "'Brave'-এর বিপরীত শব্দ নির্বাচন করুন:",
      ta: "'Brave' இன் எதிர்ச்சொல்லைத் தேர்ந்தெடுக்கவும்:",
    },
    optionsJson: [
      { en: "Bold", hi: "Bold", mr: "Bold", bn: "Bold", ta: "Bold" },
      { en: "Coward", hi: "Coward", mr: "Coward", bn: "Coward", ta: "Coward" },
      { en: "Strong", hi: "Strong", mr: "Strong", bn: "Strong", ta: "Strong" },
      { en: "Fearless", hi: "Fearless", mr: "Fearless", bn: "Fearless", ta: "Fearless" },
    ],
    correctAnswer: 1,
    explanation: {
      en: "'Coward' means lacking courage, the opposite of 'Brave'. 'Bold', 'Strong', and 'Fearless' are all synonyms or near-synonyms of 'Brave', not opposites.",
      hi: "'Coward' का अर्थ है साहस की कमी, जो 'Brave' के विपरीत है। 'Bold', 'Strong' और 'Fearless' सभी 'Brave' के समानार्थी या निकट-समानार्थी शब्द हैं, विलोम नहीं।",
      mr: "'Coward' म्हणजे धैर्याचा अभाव, जो 'Brave' च्या विरुद्ध आहे. 'Bold', 'Strong' आणि 'Fearless' हे सर्व 'Brave' चे समानार्थी किंवा जवळचे समानार्थी शब्द आहेत, विरुद्धार्थी नाहीत.",
      bn: "'Coward' মানে সাহসের অভাব, যা 'Brave'-এর বিপরীত। 'Bold', 'Strong' এবং 'Fearless' সবই 'Brave'-এর প্রতিশব্দ বা কাছাকাছি প্রতিশব্দ, বিপরীতার্থক নয়।",
      ta: "'Coward' என்றால் தைரியம் இல்லாதவர், இது 'Brave'-க்கு எதிரானது. 'Bold', 'Strong' மற்றும் 'Fearless' ஆகியவை அனைத்தும் 'Brave'-இன் ஒத்த சொற்கள், எதிர்ச்சொற்கள் அல்ல.",
    },
  },
];
